### PR TITLE
fix: fix adding/getting masks to/from MaskExtent when it is a processor

### LINKED ISSUE #2350: /mask is ignored by brush
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

When using a mask, with a brush, it seems like the mask is sometimes ignored. This does not seem to be limited to the >grass_block mask but effects at least a mask of 0 as well.

Using the brush sometimes places the grass correctly. So multiple tries might me necessary. In my testing it took a maximum of 10 attempts for it to fail. When using lapis_block it seems like it is more likely to fail.

Swapping the mask and the gmask yields a similar result as "/mask 0" is then ignored and existing blocks are replaced.

### To Reproduce

/br sphere tall_grass[half=lower] 5
/mask >grass_block
/gmask 0

OR

/br sphere lapis_block 5
/mask >grass_block
/gmask 0

Place blocks using the specified brush.

### Expected behaviour

Masks are respected when using a brush.

More specifically: Blocks are only placed on Grass Blocks and not above them.

### Screenshots / Videos

image
image

### Error log (if applicable)

_No response_

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/0bc378b6912947cfb0673488c33fd9b5

### Fawe Version

2.6.5_SNAPSHOT-521:0a19f64

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #2350

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    private final T root;
+
+    public ProcessorTraverser(@Nonnull T root) {
+        this.root = root;
+    }
+
+    @SuppressWarnings("unchecked")
+    public @Nullable <U extends IBatchProcessor> U find(Class<U> clazz) {
+        try {
+            Queue<IBatchProcessor> processors = new ArrayDeque<>(5);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:23]: Why 5?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+                processors.addAll(multiBatchProcessor.getBatchProcessors());
+            } else if (this.root instanceof BatchProcessorHolder holder) {
+                processors.add(holder.getProcessor());
+            } else {
+                return clazz.isAssignableFrom(this.root.getClass()) ? clazz.cast(this.root) : null;
+            }
+            IBatchProcessor processor;
+            while ((processor = processors.poll()) != null) {
+                if (clazz.isAssignableFrom(processor.getClass())) {
+                    return (U) processor;
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:34]:
```suggestion
                    return clazz.cast(processor);
```
This way we can get rid of the SuppressWarnings too I think

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+            Queue<IBatchProcessor> processors = new ArrayDeque<>(5);
+            if (this.root instanceof MultiBatchProcessor multiBatchProcessor) {
+                processors.addAll(multiBatchProcessor.getBatchProcessors());
+            } else if (this.root instanceof BatchProcessorHolder holder) {
+                processors.add(holder.getProcessor());
+            } else {
+                return clazz.isAssignableFrom(this.root.getClass()) ? clazz.cast(this.root) : null;
+            }
+            IBatchProcessor processor;
+            while ((processor = processors.poll()) != null) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:32]: I think this could be a do-while, reducing the duplicated code here?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+                    return (U) processor;
+                } else if (processor instanceof MultiBatchProcessor multiProcessor) {
+                    processors.addAll(multiProcessor.getBatchProcessors());
+                } else if (processor instanceof BatchProcessorHolder holder) {
+                    processors.add(holder.getProcessor());
+                }
+            }
+            return null;
+        } catch (Throwable e) {
+            e.printStackTrace();
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:43]: Should use a logger here instead, and probably add context

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+public class ProcessorTraverser<T extends IBatchProcessor> {
+
+    private final T root;
+
+    public ProcessorTraverser(@Nonnull T root) {
+        this.root = root;
+    }
+
+    @SuppressWarnings("unchecked")
+    public @Nullable <U extends IBatchProcessor> U find(Class<U> clazz) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:21]: oh and the `@Nullable` should be at the return type I guess

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java (hunk 1 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/ProcessorTraverser.java:23]: I did a quick count of the processors we almost always add, but tbh there'd realistically be no perf hit with any number

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
