### PR TITLE
fix: normalize layer when setting ordinal to ThreadUnsafeCharBlocks

### LINKED ISSUE #2763: In custom `IBatchProcessor` using `setBlock` on negative layer results in ArrayIndexOutOfBoundsException
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

I wrote my own `IBatchProcessor` to replace every set block to coal block. Example:
```java
public class FaweCustomBatchProcessor implements IBatchProcessor {
    @Override
    public IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet set) {
        int bx = chunk.getX() << 4;
        int bz = chunk.getZ() << 4;

        for (int layer = get.getMinSectionPosition(); layer <= get.getMaxSectionPosition(); layer++) {
            if (!set.hasSection(layer)) {
                continue;
            }

            // loadIfPresent shouldn't be null if set.hasSection(layer) is true
            char[] blocksSet = set.loadIfPresent(layer);

            int by = layer << 4;
            for (int y = 0, index = 0; y < 16; y++) {
                int yy = y + by;
                for (int z = 0; z < 16; z++) {
                    int zz = z + bz;
                    for (int x = 0; x < 16; x++, index++) {
                        final int rawStateSet = blocksSet[index];
                        if (rawStateSet == BlockTypesCache.ReservedIDs.__RESERVED__) continue;
                        
                        set.setBlock(x, yy, z, BlockTypes.COAL_BLOCK.getDefaultState());
                    }
                }
            }
        }

        return set;
    }

    @Nullable
    @Override
    public Extent construct(Extent child) {
        return null;
    }

    @Override
    public ProcessorScope getScope() {
        return ProcessorScope.CHANGING_BLOCKS;
    }
}
```

When I try to copy an area from top to bottom (`//expand vert`) and paste it, then blocks are not replaced and it will throw this error:
```
[19:20:26] [FAWE QueueHandler Blocking Executor - 8/ERROR]: [com.fastasyncworldedit.core.queue.implementation.blocks.ThreadUnsafeCharBlocks] Tried setting block at coordinates (12,-5,12)
[19:20:26] [FAWE QueueHandler Blocking Executor - 8/ERROR]: [com.fastasyncworldedit.core.queue.implementation.blocks.ThreadUnsafeCharBlocks] Layer variable was = -1
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 20
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.queue.implementation.blocks.ThreadUnsafeCharBlocks.set(ThreadUnsafeCharBlocks.java:228) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.queue.implementation.blocks.ThreadUnsafeCharBlocks.setBlock(ThreadUnsafeCharBlocks.java:239) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at TestPlugin.jar/com.epicplayera10.testplugin.FaweCustomBatchProcessor.processSet(FaweCustomBatchProcessor.java:56) ~[TestPlugin.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:113) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.extent.processor.MultiBatchProcessor.processSet(MultiBatchProcessor.java:93) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.extent.processor.BatchProcessorHolder.processSet(BatchProcessorHolder.java:27) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1028) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:1009) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar/com.fastasyncworldedit.core.queue.implementation.chunk.ChunkHolder.call(ChunkHolder.java:34) ~[FastAsyncWorldEdit-Bukkit-2.10.1-SNAPSHOT-785.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### To Reproduce

1. Use the custom `IBatchProcessor` above.
2. Copy section from top to bottom `//expand vert`
3. Paste it
4. See error in console

### Expected behaviour

It should replace every block with coal block and it should not show errors in the console

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/04ebdfe459a14ab48576efefc64dbd15

### Fawe Version

FastAsyncWorldEdit version 2.10.1-SNAPSHOT-790;a7e4d19

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by EpicPlayerA10**
## Overview

Fixes #2763

## Description
Adds missing `- minSectionPosition` in `set` methods. In other methods this subtraction already exists: 
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/a7e4d19605484b7eb3f2619ea270114be8fa56cf/worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/ThreadUnsafeCharBlocks.java#L208

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java [hunk 1]
```diff
@@ -204,7 +204,7 @@ public char get(int x, int y, int z) {
 
     // Not synchronized as it refers to a synchronized method and includes nothing that requires synchronization
     public void set(int x, int y, int z, char value) {
-        final int layer = y >> 4;
+        final int layer = (y >> 4) - minSectionPosition;
```
Comment (dordsor21) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java:207]: This should not be changed. The set method called afterwards applies the normalisation

Comment (EpicPlayerA10) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharBlocks.java]: Done

**Review by dordsor21 — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
