### PR TITLE
Fix queryRel returning data value for block at absolute coordinates

### LINKED ISSUE #2643: queryRel masks with data values don't work anymore
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

`queryRel` Masks don't accept data values anymore. They perform any operation without any error, but as soon as the data value in a queryRel is not 0 or -1 it doesn't do anything anymore. This is quite annoying because this eliminates half of the blocks that you can work with. As soon as one queryRel has a data value the entire mask doesn't do anything anymore.

- I tried it with different servers even with ones that only have FAWE installed
- I tried it with newest server versions and older server versions (1.19.4)
- I tried it with newest and older FAWE versions till half a year ago
- I tried it with normal WorldEdit and there it works. Only FAWE has this problem.
=> No matter what I do I can always reproduce this error with any queryRel and any mask or gmask that should produce a result but fails.

### To Reproduce

1. Select a region that contains a block with a data value (e.g. yellow wool)
2. Create a mask with queryRel (e.g. //gmask =queryRel(0,0,0,35,5) - Mask all blocks that are yellow wool)
3. Replace them (e.g. //set stone)

### Expected behaviour

The queryBlock identifies blocks with data values. 

### Screenshots / Videos

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/66020920/bc7ce129-4614-4354-aa09-0f9178fa6757

### Error log (if applicable)

no errors

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4861214b41a1481fafbb3a6b55360eab

### Fawe Version

2.9.1-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Zeranny**
## Overview
Fixes the incorrect method for relative data checks in expressions (queryRel)

Fixes #2643

## Description
Current version erroneously uses toWorld instead of toWorldRel, so `queryRel(0,0,0,t,d)` would always return the data of the block at `0,0,0` for `d`, where it should return the data value of whatever block is `0,0,0` offset.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java [hunk 1]
```diff
@@ -83,9 +83,8 @@ public int getBlockTypeRel(double x, double y, double z) {
     }
 
     @SuppressWarnings("deprecation")
-    @Override
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java:86]: The annotation should be kept

**Review by SirYwell — COMMENTED** [review]
As a side note, we should probably also pull <https://github.com/EngineHub/WorldEdit/commit/b5b9c6ab8694b7d3c4dcb435c0342d6e83c0d014> as a follow-up?

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java (hunk 1 above)
Comment (Zeranny) [reply worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java:86]: Good spot, didn't mean to remove that

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
