### PR TITLE
fix: add null-check for brush in traceMask

### LINKED ISSUE #2149: tracemask without brush set returns error
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

If I'm holding a non-brush Tool and I'm setting the tracemask, it returns an error. It should, like for a mask, return that I'm not holding a brush, and first have to put a brush on my tool to use tracemask.

### To Reproduce

- Get a tool that hasn't been made to a brush yet
- do "/tracemask #solid" for example
- Error gets thrown

### Expected behaviour

(FAWE) You aren't holding a brush!
(The return message for /mask on a non-brush)

### Screenshots / Videos

image

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4cf7cfa92fa74af298acd29d7f6175d3

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.5.2.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #2149

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]
FAWE additionally has `fawe.worldedit.brush.brush.none`, would it make sense to replace usages of that (probably in a follow-up PR)?

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java [hunk 1]
```diff
@@ -169,9 +169,14 @@ public void size(
     public void traceMask(
             Player player, LocalSession session,
             @Arg(desc = "The trace mask to set", def = "")
-                    Mask maskOpt
+            Mask maskOpt
     ) throws WorldEditException {
-        session.getBrushTool(player, false).setTraceMask(maskOpt);
+        BrushTool brushTool = session.getBrushTool(player, false);
+        if (brushTool == null) {
+            player.printError(Caption.of("worldedit.brush.none.equipped"));
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java:176]:
```suggestion
            player.print(Caption.of("worldedit.brush.none.equipped"));
```
printError doesn't listen to color codes in the lang file.

**Review by NotMyFault — APPROVED** [review]
LGTM
