### PR TITLE
Properly relight surrounding chunks

### LINKED ISSUE #3145: Lighting not being propagated in chunks bordering the pasted region
### Server Implementation

Paper

### Server Version

1.21.4

### Describe the bug

When pasting a clipboard lighting is only propagated in the chunks of the pasted region, and not neighboring chunks

### To Reproduce

1. Place Torch
2. Select Torch
3. Copy the selection
4. Paste the selection on a chunk border
5. Use F3+G and set the time to night (or look at F3) to see that the light is not propagated on bordering chunks 

### Expected behaviour

The light should be propagated the max distance of 15 blocks across chunk borders.

### Screenshots / Videos

Image
https://drive.google.com/file/d/1m70hztAfyHNqumdy7x7U-ocYUWAz1XzJ/view

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ee797284afc045629054fa914431fbd2

### Fawe Version

FastAsyncWorldEdit-1063

### Checklist

- [x] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

DC Convo: https://discord.com/channels/268444645527126017/344128526435221505/1348719853330235574

### PR DESCRIPTION
**Pull request by SirYwell**
## Overview

Fixes #3145

## Description

We need to make sure chunks bordering a change are relighted too, as light could spread into them. By just enqueuing 3x3 chunks, light is always properly recalculated now.

### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java [hunk 1]
```diff
@@ -118,10 +118,14 @@ protected void fixLighting(LongSet chunks, Runnable andThen) {
...
         try {
-            long key = MathMan.pairInt(cx >> CHUNKS_PER_BATCH_SQRT_LOG2, cz >> CHUNKS_PER_BATCH_SQRT_LOG2);
-            // TODO probably submit here already if chunks.size == CHUNKS_PER_BATCH?
-            LongSet chunks = this.regions.computeIfAbsent(key, k -> new LongArraySet(CHUNKS_PER_BATCH >> 2));
-            chunks.add(asLong(cx, cz));
+            // light can go into neighboring chunks, make sure they are relighted too.
+            for (int x = cx - 1; x <= cx + 1; x++) {
+                for (int z = cz - 1; z <= cz + 1; z++) {
+                    long key = MathMan.pairInt(x >> CHUNKS_PER_BATCH_SQRT_LOG2, z >> CHUNKS_PER_BATCH_SQRT_LOG2);
+                    LongSet chunks = this.regions.computeIfAbsent(key, k -> new LongArraySet(CHUNKS_PER_BATCH >> 2));
```
Comment (dordsor21) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java:125]: Just a thought, is this/does this need to be concurrent?

Comment (SirYwell) [reply worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java:125]: Multiple threads might add chunks here concurrently, yes

Comment (SirYwell) [reply worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/StarlightRelighter.java:125]: We hold the areaLock, that should be enough

**Review by NotMyFault — APPROVED** [review]

**Comment by zechatmachine-hub** [comment]
hi, 
i still got the issue on 2.15.0
image

close to the pasted zone the block in my hand is lighted
image
just a bit farther to the pasted zone the block in my hand is not lighted anymore
image
