### PR TITLE
fix: Run GriefPrevention region check in sync

### LINKED ISSUE #1692: error using fawe inside a griefprevention's claim
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

If i use fawe commands inside a griefprevention's claim, i have errors in console

### To Reproduce

go inside a griefprevention's claim
use fawe commands (copy paste move)

### Expected behaviour

actually it seems to regularly work but cannot be sure, only errors in console, spams a lot

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://paste.gg/p/anonymous/7167558b5c544e5fa2d420e890006cf9

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/98bf44e1bd614d7c9d36d57899d4988a

### Fawe Version

2.1.1 dev 149

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NotMyFault**
## Overview

Fixes #1692

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [ ] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java [hunk 1]
```diff
@@ -26,10 +27,11 @@ public GriefPreventionFeature(final Plugin griefpreventionPlugin) {
     }
 
     public boolean isAllowed(Player player, Claim claim, MaskType type) {
-        return claim != null && (claim.getOwnerName().equalsIgnoreCase(player.getName()) || claim
+        return TaskManager.taskManager().sync(() -> claim != null && (claim.getOwnerName().equalsIgnoreCase(player.getName()) || claim
                 .getOwnerName()
                 .equals(player.getUniqueId()) ||
-                type == MaskType.MEMBER && claim.allowBuild(player, Material.AIR) == null);
+                type == MaskType.MEMBER && claim.allowBuild(player, Material.AIR) == null));
```
Comment (dordsor21) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/GriefPreventionFeature.java:33]: Is it better worth putting the sync only on the final "or" of this as the rest doesn't need the added overhead of executing on main

**Review by SirYwell — APPROVED** [review]
