### PR TITLE
Don't allow edits on plots when owner is offline and player is only added

### LINKED ISSUE #1037: PS: added player can use worldedit when owner offline
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Added players on a PS plot can still use worldedit even if the plot owner is offline.

### To Reproduce

1. Add a player on a plot
2. Log off the owner off the plot
3. The other Player can still use WorldEdit (can't use axe to set 2 position, need to use `//pos2`)
4. Even after a restart the added player can still use WoeldEdit

### Expected behaviour

The player should not be able to use WorldEdit on the plot when the owner is offline.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/104bf9e2a4564aa5998e8b5d3d2424f0

### Fawe Version

FastAsyncWorldEdit version 1.16-666;ceacd7b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Plotsquared Version: PlotSquared version 5.13.11-Premium

### PR DESCRIPTION
**Pull request by dordsor21**
Fixes #1037

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java [hunk 1]
```diff
@@ -68,10 +69,20 @@ public boolean isAllowed(Player player, Plot plot, MaskType type) {
...
-        return !plot.getFlag(NoWorldeditFlag.class) && (plot.isOwner(uid) || type == MaskType.MEMBER && (
-                plot.getTrusted().contains(uid) || plot.getTrusted().contains(DBFunc.EVERYONE)
-                        || (plot.getMembers().contains(uid) || plot.getMembers().contains(DBFunc.EVERYONE)) && player
-                        .hasPermission("fawe.plotsquared.member")) || player.hasPermission("fawe.plotsquared.admin"));
+        return !plot.getFlag(NoWorldeditFlag.class) && (plot.isOwner(uid) || player.hasPermission("fawe.plotsquared.admin")
+                || type == MaskType.MEMBER && (plot.getTrusted().contains(uid) || plot.getTrusted().contains(DBFunc.EVERYONE)
+                || (player.hasPermission("fawe.plotsquared.member")
+                && (plot.getMembers().contains(uid) || plot.getMembers().contains(DBFunc.EVERYONE))
+                && !plot.getOwners().isEmpty()
+                && plot.getOwners().stream().anyMatch(this::playerOnline))));
```
Comment (NotMyFault) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java:77]: Preferably we should drop a `TranslatableCaption` outlining why you can't use FAWE if one of the conditions aren't matched. Failing silently might be hard to debug until you find that specific page on the wiki listing the permissions for FAWE & P2.

**Review by NotMyFault — CHANGES_REQUESTED** [review]

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java (hunk 1 above)
Comment (dordsor21) [reply worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java:77]: Likely to be sending two messages to players in that case

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]
