### PR TITLE
Remove hardcoding of world limits

### LINKED ISSUE #1134: [1.17] Actions performed above y = 256 and below y = 0 do not work
### Server Implementation

Paper

### Server Version

1.17

### Describe the bug

Performing an edit outside of the range 0-256 will result in an error. Minecraft versions before 1.17 were previously limited to a world height of 256. The game now allows negative y values and an increased height range.

No blocks are set with any command. An error appears every time a block is set outside of the 0-256 height range.

### To Reproduce

1. Load up FAWE on a Paper server
2. Try to set any blocks outside of the 0-256 height range. 
3. Observe that nothing happens
4. Look into the console

### Expected behaviour

I would expect the blocks to be set, and an error wouldnt appear in console.

### Screenshots / Videos

Tried to set air to the grass, nothing happened and an error appeared in console.

### Error log (if applicable)

https://gist.github.com/DaJokni/3310dfda3c8f934bef4ddd8a3ecbf5c2

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/dab33e1e6ac64d90a561a672d7f5019a

### Fawe Version

FastAsyncWorldEdit version 1.17-10;dec29c8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- seems to be working fine without the datapack for world height changing
- particular attention should be given to LocalBlockVectorSet and MathMan changes
- various functions will currently only work with a ymax-ymin of 512 blocks
- Fixes #1134

### CODE REVIEW

**Comment by NotMyFault** [comment]
After testing it in my plotworld https://paste.gg/p/anonymous/d3dc4fde7bd040f1bb6ec9968920fe2e

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/RelightProcessor.java [hunk 1]
```diff
@@ -28,11 +28,12 @@ public IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet set) {
         if (Settings.IMP.LIGHTING.MODE == 2) {
             relighter.addChunk(chunk.getX(), chunk.getZ(), null, chunk.getBitMask());
         } else if (Settings.IMP.LIGHTING.MODE == 1) {
-            byte[] fix = new byte[16];
+            byte[] fix = new byte[get.getMaxLayer() - get.getMinLayer()];
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/RelightProcessor.java:31]: Misses a  `+ 1` if `getMaxLayer()` is inclusive

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java [hunk 2]
```diff
@@ -189,11 +189,11 @@ protected void generateCaveNode(
...
             }
 
-            if (i1 < 1) {
-                i1 = 1;
+            if (i1 < chunk.getMinY() + 1) {
+                i1 = chunk.getMinY();
             }
-            if (i2 > 256 - 8) {
-                i2 = 256 - 8;
+            if (i2 > chunk.getMaxY() - 8) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java:195]: If `getMaxY` is inclusive, the old code is either wrong or a  `+ 1` is needed

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AdjacentAnyMask.java [hunk 3]
```diff
@@ -44,9 +48,9 @@ public BlockVector3 direction(BlockVector3 v) {
             return mutable.setComponents(0, 0, 1);
         } else if (mask.test(x, y, z - 1)) {
             return mutable.setComponents(0, 0, -1);
-        } else if (y < 256 && mask.test(x, y + 1, z)) {
+        } else if (y < maxY && mask.test(x, y + 1, z)) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AdjacentAnyMask.java:51]: inclusive or exclusive? Might miss a `+ 1`

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java [hunk 4]
```diff
@@ -71,7 +71,7 @@ public abstract void filter(
      */
     public final IChunkSet filter(IChunk chunk, IChunkGet get, IChunkSet set, Filter filter) {
         initChunk(chunk.getX(), chunk.getZ());
-        for (int layer = 0; layer < 16; layer++) {
+        for (int layer = get.getMinLayer(); layer < get.getMaxLayer(); layer++) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java:74]: Missing `+ 1` if inclusive

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java [hunk 5]
```diff
@@ -87,7 +87,7 @@ public final IChunkSet filter(IChunk chunk, IChunkGet get, IChunkSet set, Filter
         if (region != null) {
             region.filter(chunk, filter, this, get, set, full);
         } else {
-            for (int layer = 0; layer < 16; layer++) {
+            for (int layer = get.getMinLayer(); layer < get.getMaxLayer(); layer++) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/ChunkFilterBlock.java:90]: Same as above

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java [hunk 6]
```diff
@@ -418,6 +419,8 @@ public IntPair readHeader() {
                 final FaweInputStream gis = MainUtil.getCompressedIS(fis);
                 // skip mode
                 gis.skipFully(1);
+                // skip version
+                gis.skipFully(1);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java:423]: What happens when reading files without version? Or is that just impossible?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java [hunk 7]
```diff
@@ -157,7 +157,7 @@ public synchronized IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet
                 addEntityCreate(tag);
             }
         }
-        for (int layer = 0; layer < 16; layer++) {
+        for (int layer = get.getMinLayer(); layer < get.getMaxLayer(); layer++) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:160]: `+ 1` if inclusive

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java [hunk 8]
```diff
@@ -195,7 +196,7 @@ public synchronized IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet
 
         BiomeType[] biomes = set.getBiomes();
         if (biomes != null) {
-            for (int y = 0, index = 0; y < 64; y++) {
+            for (int y = get.getMinLayer() << 2, index = 0; y < get.getMaxLayer() << 2; y++) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:199]: `+ 1` before shifting if max is inclusive

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java [hunk 9]
```diff
@@ -11,14 +11,14 @@
 
 /**
  * The LocalBlockVectorSet is a Memory and CPU optimized Set for storing BlockVectors which are all in a local region
- * - All vectors must be in a 2048 * 2048 area centered around the first entry
+ * - All vectors must be in a 2048 * 2048 * 512 area centered around the first entry
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java:14]: `x * y * z`

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java [hunk 10]
```diff
@@ -43,7 +45,23 @@ protected Mask parseFromInput(@Nonnull String[] arguments, ParserContext context
...
+            int miny;
+            int maxy;
+            if (context.getActor() instanceof Player) {
+                World world = ((Player) context.getActor()).getWorld();
+                miny = world.getMinY();
+                maxy = world.getMaxY();
+            } else if (context.getWorld() != null) {
+                miny = context.getWorld().getMinY();
+                maxy = context.getWorld().getMaxY();
+            } else if(context.getExtent() != null) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java:57]: Formatting

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java [hunk 11]
```diff
@@ -43,7 +45,23 @@ protected Mask parseFromInput(@Nonnull String[] arguments, ParserContext context
             max = min;
         }
         if (max >= 8 && min == 1) {
-            return new AdjacentAnyMask(subMask);
+            int miny;
+            int maxy;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java:49]: Camel casing? Afaik, minY, maxY is what's been used in more spots.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java [hunk 12]
```diff
@@ -227,6 +241,10 @@ public void writeHeader(OutputStream os, int x, int y, int z) throws IOException
     public void readHeader(InputStream is) throws IOException {
         // skip mode
         int mode = is.read();
+        int version = is.read();
+        if (version != FaweStreamChangeSet.version) {
+            throw new UnsupportedOperationException(String.format("Version %s history not supported!", version));
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java:246]: Maybe drop some instructions how to mitigated that?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java [hunk 13]
```diff
@@ -288,4 +306,48 @@ public IChunkSet reset() {
...
+        checkLayer(layer);
+        return super.load(layer);
+    }
+
+    @Override
+    public int getLayerCount() {
+        return layers;
+    }
+
+    private void checkLayer(int layer) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java:320]: Method name does not really tell what's going on here

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java [hunk 14]
```diff
@@ -152,41 +152,47 @@ public static long pairInt(int a, int b) {
...
+        return (triple & 0x1ff) - 256;
     }
 
     public static int untripleBlockCoordZ(int triple) {
-        return (triple >> 8) & 0xF;
+        return (triple >> 12) & 0xF;
     }
 
+    /**
+    * @deprecated does not support 0>y>255
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java:193]: If that's been replace by `tripleSearchCoordsExtendedY`, link it.

File: worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java [hunk 15]
```diff
@@ -1182,6 +1182,16 @@ public int size() {
...
+    @Override
+    public BlockVector3 getMinimumPoint() {
+        return getWorld().getMinimumPoint();
+    }
+
+    @Override
+    public BlockVector3 getMaximumPoint() {
+        return getWorld().getMaximumPoint();
+    }
+
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java:1194]: Missing annotation, see one line below where it starts.

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java [hunk 16]
```diff
@@ -258,7 +258,7 @@ public void chunk(
                     .clampY(minChunkY, maxChunkY);
 
             min = minChunk.shl(CHUNK_SHIFTS, CHUNK_SHIFTS_Y, CHUNK_SHIFTS);
-            max = maxChunk.shl(CHUNK_SHIFTS, CHUNK_SHIFTS_Y, CHUNK_SHIFTS).add(15, world.getMaxY(), 15);
+            max = maxChunk.shl(CHUNK_SHIFTS, CHUNK_SHIFTS_Y, CHUNK_SHIFTS).add(15, 255, 15);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java:261]: Why was this changed back?

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java [hunk 17]
```diff
@@ -286,7 +286,7 @@ public void chunk(
             }
 
             min = minChunk.shl(CHUNK_SHIFTS, CHUNK_SHIFTS_Y, CHUNK_SHIFTS);
-            max = min.add(15, world.getMaxY(), 15);
+            max = min.add(15,255, 15);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java:289]: Formatting + previous comment.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java [hunk 18]
```diff
@@ -200,6 +206,33 @@ public static int tripleSearchCoords(int x, int y, int z) {
...
+     * Obtain an integer representation of 3 ints, x, y and z. y is represented by the right-most 9 bits and can
+     * be within the range -256 to 255. x and z are represented by 11 bits each and can be within the range
+     * -1024 to 1024
+     *
+     * @param x x value
+     * @param y y value
+     * @param z z value
+     * @return integer representation of x y z
+     */
+    public static int tripleSearchCoordsExtendedY(int x, int y, int z) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java]: Why aren't we using 10 bits for y here?

**Review by NotMyFault — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java (hunk 12 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/FaweStreamChangeSet.java:246]: Since we're breaking history compatibility anyway, I figured I'd just add it in now in case it's useful in the future. There'll only be the one version to start with lol

File: worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java (hunk 15 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/EditSession.java:1194]: Which annotation? The methods exist in WE EditSession

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java (hunk 16 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java:261]: The description of the command specifically states //chunk will select in a 256 block range, and upstream uses 255 currently.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java [hunk 19]
```diff
@@ -200,6 +206,33 @@ public static int tripleSearchCoords(int x, int y, int z) {
...
+        if (x > 1023 || x < -1024 || y > 255 || y < -256 || z > 1023 || z < -1024) {
+            throw new IndexOutOfBoundsException(String.format("Check range on x=%s, y=%s and z=%s!", x, y, z));
+        }
+        byte b1 = (byte) (y & 0xff);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java:206]: This looks more complex than needed. What's wrong with
```java
return (z << 21) | ((x & 0x7ff) << 10) | (y & 0x3ff);
```
?
If this method is just used for hashing, that's already fine, if the coordinates should be extracted again, it would make sense to add the minimum before the OR to easily deal with negative values.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java [hunk 20]
```diff
@@ -152,52 +152,68 @@ public static long pairInt(int a, int b) {
...
 
     public static int untripleBlockCoordZ(int triple) {
-        return (triple >> 8) & 0xF;
+        return (triple >> 12) & 0xF;
     }
 
+    /**
+     * Obtain an integer representation of 3 ints, x, y and z. y is represented by the right-most 9 bits and can
+     * be within the range -256 to 255. x and z are represented by 11 bits each and can be within the range
+     * -1024 to 1024
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java:195]: -1024 to 1023, and we can use 10 bits for y (see my comment below, I assumed 10 bits there)

**Review by SirYwell — CHANGES_REQUESTED** [review]
Some inconsistencies with inclusive/exclusive upper bounds

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java (hunk 16 above)
Comment (NotMyFault) [reply worldedit-core/src/main/java/com/sk89q/worldedit/command/SelectionCommands.java:261]: Interesting, but going by description of the command, you can already use these commands out of the typical range.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AdjacentAnyMask.java (hunk 3 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/AdjacentAnyMask.java:51]: wrong previously. 255+1=256 which fails

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java (hunk 6 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java:423]: It will be impossible. Since we're breaking history compatibility anyway, I figured I'd just add it in now in case it's useful in the future. There'll only be the one version to start with lol

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java (hunk 18 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java]: Can't use the 32nd bit of an integer if we still want to use it as an index for arrays

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java (hunk 11 above)
Comment (MattBDev) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/AdjacentMaskParser.java]: Agreed. 🐫 Casing please.

**Comment by dordsor21** [comment]
History doesn't seem to work and I want to look further into LocalBlockVectorSet which will wait till tomorrow or later

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java (hunk 18 above)
Comment (SirYwell) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java]: I see. Should be documented then I think

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java (hunk 19 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java]: It needs to accept negative values. Coordinates do need to be extracted again. The current way in the PR is better in keeping with how it does done previously, though if there's a method that also works I'm open to it - just PR it as I';ve not got time to think about it for a while...

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java (hunk 2 above)
Comment (MattBDev) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java]: Yeah. All the inclusive and exclusive stuff needs to be clarified all over it looks like.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java (hunk 13 above)
Comment (MattBDev) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/blocks/CharSetBlocks.java]: Documentation needed.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java (hunk 18 above)
Comment (MattBDev) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java]: > I see. Should be documented then I think

Agreed.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java [hunk 21]
```diff
@@ -152,52 +152,65 @@ public static long pairInt(int a, int b) {
...
     }
 
     public static int untripleBlockCoordZ(int triple) {
-        return (triple >> 8) & 0xF;
+        return (triple >> 12) & 0xF;
     }
 
+    /**
+     * Obtain an integer representation of 3 ints, x, y and z. y is represented by the right-most 9 bits and can
+     * be within the range -256 to 255. x and z are represented by 11 bits each and can be within the range
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/MathMan.java:194]: Is -256 to 255 inclusive or exclusive? This needs to be clarified.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkGet.java [hunk 22]
```diff
@@ -63,4 +63,24 @@ default IChunkGet getCopy() {
 
     void setHeightmapToGet(HeightMapType type, int[] data);
 
+    /**
+     * Max world y (inclusive)
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkGet.java:67]: Is this the max world y or the max y for the chunk?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java (hunk 2 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java]: This is a resolved, outdated comment 🙄

Comment (MattBDev) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/function/generator/CavesGen.java]: I only just finished my review a wrote a couple of days ago. Sry

**Comment by NotMyFault** [comment]
Tested on caves and cliffs 2, every edit -> https://paste.gg/p/anonymous/f4549320eccb482f8563ff78aebaf12d

**Comment by dordsor21** [comment]
Well _**STARLIGHT**_ works lol

**Comment by NotMyFault** [comment]
> Well _**STARLIGHT**_ works lol

Also works on Paper, you just need to relog after every edit lol

**Comment by MeFisto94** [comment]
Another thing related to that: In theory there are light sections, that are, in theory, different from the block sections.
Currently, they are equal, but who knows what the future holds.
See [my PR to paper](https://github.com/PaperMC/Paper/pull/6266/files#diff-13e68c3aca0f3648416040218b879b3fe9e2135556c4866e484c82e59e90a2f0R181-R214)

**Comment by NotMyFault** [comment]
Tested with the Caves & Cliffs datapack, I encountered the following issues so far:
- `//regen` producing https://paste.gg/p/anonymous/bfb3de3ee26b4e15bb39d39c73d2514f
- `//up` only working within 0 -> 255
- `//removebelow & //removeabove` claiming blocks have been removed but no change to the world has been made

**Comment by dordsor21** [comment]
> * `//removebelow & //removeabove` claiming blocks have been removed but no change to the world has been made

Don't think these have been working for a long time...

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/HollowCylinderBrush.java [hunk 23]
```diff
@@ -28,9 +28,11 @@
 public class HollowCylinderBrush implements Brush {
 
     private final int height;
+    private final double thickness;
 
-    public HollowCylinderBrush(int height) {
+    public HollowCylinderBrush(int height, double thickness) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/tool/brush/HollowCylinderBrush.java:33]: Fawe annotations

File: worldedit-core/src/main/java/com/sk89q/worldedit/extension/input/ParserContext.java [hunk 24]
```diff
@@ -270,5 +273,57 @@ public void setInjected(InjectedValueAccess injected) {
     public InjectedValueAccess getInjected() {
         return injected;
     }
+
+    public int getMinY() {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/extension/input/ParserContext.java:277]: Javadocs?

File: worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/BreadthFirstSearch.java [hunk 25]
```diff
@@ -83,12 +83,14 @@
     }
     //FAWE end
 
-    private final RegionFunction function;
+    protected final RegionFunction function;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/BreadthFirstSearch.java:86]: Annotations

File: worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java [hunk 26]
```diff
@@ -37,21 +37,9 @@
...
-     * @param baseY    the base Y
-     */
-    public DownwardVisitor(Mask mask, RegionFunction function, int baseY) {
-        this(mask, function, baseY, Integer.MAX_VALUE);
-    }
-    //FAWE end
-
-    public DownwardVisitor(Mask mask, RegionFunction function, int baseY, int depth) {
-        super(mask, function, depth);
+    public DownwardVisitor(Mask mask, RegionFunction function, int baseY, int depth, int minY, int maxY) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java:40]: Where did the javadocs go to?

Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java:40]: Where did the javadocs go to?

File: worldedit-core/src/main/resources/lang/strings.json [hunk 27]
```diff
@@ -491,6 +495,7 @@
 
     "worldedit.cyl.invalid-radius": "You must either specify 1 or 2 radius values.",
     "worldedit.cyl.created": "{0} blocks have been created.",
+    "worldedit.hcyl.thickness-too-large": "Thickness cannot be larger than x or z radii.",
```
Comment (NotMyFault) [inline worldedit-core/src/main/resources/lang/strings.json:498]: I started to name out additions with `fawe.`. Maybe we should continue doing so.

**Review by NotMyFault — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java [hunk 28]
```diff
@@ -346,6 +354,8 @@ public void add(int x, int y, int z, int combinedFrom, BaseBlock to) {
         Runnable wrappedTask = () -> {
             try {
                 writeTask.run();
+            } catch (Throwable t) {
+                t.printStackTrace();
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:358]: This should use a logger and in best case not catch errors that can't be ignored

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java [hunk 29]
```diff
@@ -23,49 +23,51 @@
 
 public class BiomeMath {
 
-    // From BiomeArray / BiomeContainer
-    public static final int HORIZONTAL_SECTION_COUNT = (int) Math.round(Math.log(16.0D) / Math.log(2.0D)) - 2;
-    public static final int VERTICAL_SECTION_COUNT = (int) Math.round(Math.log(256.0D) / Math.log(2.0D)) - 2;
-    public static final int HORIZONTAL_BIT_MASK = (1 << HORIZONTAL_SECTION_COUNT) - 1;
-    public static final int VERTICAL_BIT_MASK = (1 << VERTICAL_SECTION_COUNT) - 1;
+    //FAWE - Removed because its bad.
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java:26]: Any explanation for anyone coming across this?

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java (hunk 28 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:358]: Without this, anything thrown in the writeTask is not necessarily made visible in the console - something I came across whilst trying to work out why history wasn't working

Comment (SirYwell) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:358]: What do you think about logging the stacktrace and rethrowing? I'd prefer that personally

Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/history/changeset/AbstractChangeSet.java:358]: Rethrowing would only make sense if completenow is false, and probably in that case shouldn't be printed here in the first place. Rethrowing if it's true will do nothing because this is the too of the task chain so nothing else is going to be done as the runnable is submitted unblockingly

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java [hunk 30]
```diff
@@ -244,11 +244,11 @@ default void filter(
...
             boolean full
     ) {
-        int minSection = Math.max(0, getMinimumY() >> 4);
-        int maxSection = Math.min(15, getMaximumY() >> 4);
+        int minSection = Math.max(get.getMinSectionIndex(), getMinimumY() >> 4);
+        int maxSection = Math.min(get.getMaxSectionIndex(), getMaximumY() >> 4);
         block = block.initChunk(chunk.getX(), chunk.getZ());
         for (int layer = minSection; layer <= maxSection; layer++) {
-            if ((!full && !get.hasSection(layer)) || !filter.appliesLayer(chunk, layer)) {
+            if ((!full && !set.hasSection(layer)) || !filter.appliesLayer(chunk, layer)) {
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java:251]: Is this a bug fix or unintentional?

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java [hunk 31]
```diff
@@ -19,53 +19,54 @@
...
-
-    /**
-     * Compute the index into the MC biome array, for non-extended-height worlds.
-     *
-     * @param x the block x coordinate
-     * @param y the block y coordinate
-     * @param z the block z coordinate
-     * @return the index into the standard MC biome array
-     */
-    public static int computeBiomeIndex(int x, int y, int z) {
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java:43]: Removing these, even if they are in the internal package is a major upstream compatibility breakage. All the public methods should just return 0 .

**Review by MattBDev — CHANGES_REQUESTED** [review]
If there is a place where I asked for a javadoc where there is a max/minY it doesn't need to be a complete javadoc. it could just have the parameters documented and nothing else.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/LimitExtent.java [hunk 32]
```diff
@@ -119,92 +119,92 @@ public boolean regenerateChunk(int x, int z, @Nullable BiomeType type, @Nullable
 
     @Override
     public int getHighestTerrainBlock(int x, int z, int minY, int maxY) {
-        limit.THROW_MAX_CHECKS(FaweCache.IMP.WORLD_HEIGHT);
+        limit.THROW_MAX_CHECKS(maxY - minY + 1);
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/LimitExtent.java:122]: I had thought it was quite obvious what was going on with any "THROW_MAX_CHECKS" etc. methods. Commenting on every single one would be very excessive... Adding javadocs to every method touched by the PR is also a bit excessive...

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/heightmap/HeightMap.java [hunk 33]
```diff
@@ -166,20 +167,22 @@ default void applyHeightMapData(
...
                     oldData[index] = height;
-                    if (height == 0) {
+                    if (height == minY) {
                         newData[index] = centerY;
                         continue;
                     }
                     raise = (yscale * raise);
-                    int random = ThreadLocalRandom.current().nextInt(256) < (int) ((raise - (int) raise) * (256)) ? 1 : 0;
+                    int random =
+                            ThreadLocalRandom.current().nextInt(maxY + 1 - minY) - minY < (int) ((raise - (int) raise) * (maxY - minY + 1))
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/heightmap/HeightMap.java:184]: double - int is not necessarily zero.

File: worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/NonRisingVisitor.java [hunk 34]
```diff
@@ -28,22 +28,19 @@
...
+    //FAWE start - int depth
 
     /**
      * Create a new recursive visitor.
      *
      * @param mask     the mask
      * @param function the function
+     * @param depth    max number of recursions
+     * @param minY     min applicable y
+     * @param maxY     max applicable y
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/NonRisingVisitor.java:40]: "applicable". Heavily implies indlusive.

File: worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java [hunk 35]
```diff
@@ -37,21 +37,19 @@
...
-
     /**
      * Create a new visitor.
      *
      * @param mask     the mask
      * @param function the function
      * @param baseY    the base Y
+     * @param depth    maximum number of iterations
+     * @param minY     minimum allowable y to visit
+     * @param maxY     maximum allowable y to visit
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java:48]: It's quite obvious that it's inclusive

File: worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/OffsetMask.java [hunk 36]
```diff
@@ -31,6 +31,10 @@
  */
 public class OffsetMask extends AbstractMask {
 
+    //FAWE start - ignore resultant position outside world height range
+    private final int minY;
+    private final int maxY;
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/OffsetMask.java:36]: they're all inclusive. Everywhere. Always.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkSet.java [hunk 37]
```diff
@@ -107,4 +107,6 @@ default Operation commit() {
         return null;
     }
 
+    boolean hasBiomes(int layer);
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/IChunkSet.java:110]: Adding all the javadocs to classes that don't have them is a PR in itself... :/ One of many methods in this class has javadocs.

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java (hunk 31 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java:43]: it's in the internal package so should be considered very much not API.

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 38]
```diff
@@ -234,16 +236,18 @@ private void setupWorldData() {
...
 
     @SuppressWarnings({"deprecation", "unchecked"})
     private void initializeRegistries() {
-        // Biome
+        /* FAWE start - move Biomes to their own method
         for (Biome biome : Biome.values()) {
             String lowerCaseBiomeName = biome.name().toLowerCase(Locale.ROOT);
             BiomeType.REGISTRY.register("minecraft:" + lowerCaseBiomeName, new BiomeType("minecraft:" + lowerCaseBiomeName));
         }
+        /* FAWE end
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:250]: This would break all consequent commenting..

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/NMSRelighter.java [hunk 39]
```diff
@@ -1244,15 +1248,15 @@ public void smoothSkyLight(RelightSkyEntry chunk, int y, boolean direction) {
         public int bitmask;
         public boolean smooth;
 
-        public RelightSkyEntry(int x, int z, byte[] fix, int bitmask) {
+        public RelightSkyEntry(int x, int z, byte[] fix, int bitmask, int minY, int maxY) {
```
[the remark this answers is not in the document]
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/processor/lighting/NMSRelighter.java:1251]: Not even close to being API.

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java (hunk 30 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/sk89q/worldedit/regions/Region.java:251]: bug fix

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java (hunk 31 above)
Comment (MattBDev) [reply worldedit-core/src/main/java/com/sk89q/worldedit/internal/util/BiomeMath.java:43]: I'll mark this as resolved but I hope it doesn't come to bite us in the butt.

**Review by MattBDev — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]
