### PR TITLE
Fix compatibility with WorldGuard

### LINKED ISSUE #2738: Newer WorldGuard Builds now break since methods are missing in FastAsyncWorldEdit
### Server Implementation

Paper

### Server Version

1.20.5/6

### Describe the bug

Within recent WorldGuard builds, there is an issue to where now it causes WorldGuard to fail because ``com.sk89q.worldedit.math.BlockVector2.x()`` does not exist in current FastAsyncWorldEdit builds, which is now required in newer builds of WorldGuard.

Note that I have tested this on a test server and not in production.

### To Reproduce

1. Download latest experimental build of WorldGuard from https://builds.enginehub.org/job/worldguard/24198 (as of this bug report)
2. Download latest build of FastAsyncWorldEdit from https://ci.athion.net/job/FastAsyncWorldEdit/
3. Grab the latest Paper Build
4. Start the server
5. Error should generate
6. Region data will fail and WorldGuard will disable, thus breaks any other plugin that relies on WorldGuard

### Expected behaviour

Should load region data, if there is any and continue to load the server without issues.

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://paste.gg/p/anonymous/d05b9fbce43242b787832fb640b1c56e

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/7dec0193f5ad4a839dfb2b484d4ef505

### Fawe Version

FastAsyncWorldEdit v.2.10.0;d8eb03f

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Running Paper version 1.20.6-82-master@0ad09de as of writing this bug report if that helps out

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Basically, integrates the record updates from upstream in a kind of fitting matter (due to use of abstract classes only "simulated" records).
Started updating references to the now deprecated methods, but there are a few hundreds left - which can be addressed on the fly when working on other things or if someone want's to do that. Works right now, but will extend the amount of deprecation warnings quite a bit (as if that matters lol)

WorldGuard seems to run, and basic WE commands as well(?)

Fixes #2738
Partially addresses #2740

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java [hunk 1]
```diff
@@ -135,57 +137,69 @@ public MutableBlockVector3 setComponents(int x, int y, int z) {
...
 
     /**
      * Get the X coordinate.
      *
      * @return the x coordinate
+     * @deprecated use {@link #x()} instead
      */
-    //FAWE start - getter
+    @Deprecated(forRemoval = true)
+    public int getX() {
```
Comment (dordsor21) [inline worldedit-core/src/main/java/com/sk89q/worldedit/math/BlockVector3.java:189]: `@since` tabs

File: worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector2.java [hunk 2]
```diff
@@ -83,11 +80,22 @@ public Vector2 withX(double x) {
         return Vector2.at(x, z);
     }
 
+    /**
+     * Get the Z coordinate, aligned to the block grid.
+     *
+     * @return the block-aligned z coordinate
+     */
+    public int blockZ() {
```
Comment (dordsor21) [inline worldedit-core/src/main/java/com/sk89q/worldedit/math/Vector2.java:88]: Since tags here too

**Review by dordsor21 — COMMENTED** [review]
Just the since tags, otherwise, I wonder if we want/need to keep hashcodes the same as upstream? Should also put the FAWE start/end comments around those

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
