### PR TITLE
Fix error on adapting custom entities / entity types

### LINKED ISSUE #2673: Spawn a ModelEngine Model Send a Error
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

fawe

### To Reproduce

Summoning a model into the world with ModelEngine will result in this error,Not all models will be generated, and I can provide you with the one that generates the error

### Expected behaviour

solved!

### Screenshots / Videos

https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/71014798/5718bc71-c885-4172-a344-19d7ca447cd0

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/d0dbc23589304a318b2cd29118b807e6

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.9.3-SNAPSHOT-722

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #2673

## Description
Remove usage of deprecated getName on EntityType enum - use code from upstream to be more in line with WE API
I have not tested these changes yet, but see no issue in them either.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java [hunk 1]
```diff
@@ -343,7 +347,7 @@ default GameMode adapt(org.bukkit.GameMode gameMode) {
      * @return WorldEdit EntityType
      */
     default EntityType adapt(org.bukkit.entity.EntityType entityType) {
-        return EntityTypes.get(entityType.getName().toLowerCase(Locale.ROOT));
+        return EntityTypes.get(entityType.getKey().toString());
```
Comment (PierreSchwang) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java:350]: Original: https://github.com/EngineHub/WorldEdit/blob/master/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java#L396

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java [hunk 2]
```diff
@@ -186,10 +188,12 @@ default Material adapt(BlockType blockType) {
...
     default org.bukkit.entity.EntityType adapt(EntityType entityType) {
-        if (!entityType.getId().startsWith("minecraft:")) {
-            throw new IllegalArgumentException("Bukkit only supports vanilla entities");
+        NamespacedKey entityKey = NamespacedKey.fromString(entityType.toString());
+        if (entityKey == null) {
+            throw new IllegalArgumentException("Entity key '" + entityType + "' does not map to Bukkit");
         }
-        return org.bukkit.entity.EntityType.fromName(entityType.getId().substring(10).toLowerCase(Locale.ROOT));
+
+        return Registry.ENTITY_TYPE.get(entityKey);
```
Comment (PierreSchwang) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java:196]: Original https://github.com/EngineHub/WorldEdit/blob/79a06b1d21bacfb8b6ab1df1c2452da119fdddf4/worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitAdapter.java#L399-L406
(EntityType is not an record on our end - which theoretically breaks compatibility - so I've used toString instead of the id accessor. Might be worth adding that method to simulate the record behavior?)

**Review by TheMeinerLP — APPROVED** [review]
LGTM

**Review by dordsor21 — APPROVED** [review]
