### PR TITLE
Fixes command context for bukkit console command sender

### LINKED ISSUE #1994: Cannot use //confirm command in console
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When I do the FAWE operations from the console, and something needs confirmation, the `//confirm` command always returns `You have no actions pending confirmation.` error.

After this error occurred on my main server, I also tried running it on a local server with no other plugins - the same result.

### To Reproduce

1. Open your server's console
2. Select a large part of your world using `//pos1` and `//pos2` (or `//1` and `//2`)
3. Try to modify this selected area. For example: //replace lava water
4. FAWE will give you a confirmation request. Example: `Your selection is large ((0, 0, 0) -> (1000, 0, 1000), containing 101000 blocks). Use //confirm to execute /replace lava water`
5. Type `//confirm`  in the console.
6. You get the `You have no actions pending confirmation.` error.

### Expected behaviour

FAWE should execute the command and start the requested process.

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://gist.github.com/GodDirtman/412100af5b6ce1317eca072f4171031c

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9e6211532cf846c4bd8abf623b408ceb

### Fawe Version

2.4.9-SNAPSHOT-296;0d112b2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TheMeinerLP**
## Overview

Fixes #1994 

## Description
Thanks to @GiantTreeLP to help me to identify the issue with the console command sender from fawe/worldedit.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 1]
```diff
@@ -112,11 +112,15 @@ public class WorldEditPlugin extends JavaPlugin {
     private BukkitServerInterface platform;
     private BukkitConfiguration config;
     private BukkitPermissionAttachmentManager permissionAttachmentManager;
+    // Fawe start
+    private BukkitCommandSender bukkitConsoleCommandSender;
+    // Fawe stop
```
Comment (PierreSchwang) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:117]: `stop` -> `end`

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 2]
```diff
@@ -312,7 +316,7 @@ private void setupTags() {
                     "The version of Spigot/Paper you are using doesn't support Tags. The usage of tags with WorldEdit will not work until you update.");
         }
     }
-
+//575AFD72384E9CF4B59175B4502E5637
```
Comment (PierreSchwang) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:319]: ?

**Review by PierreSchwang — CHANGES_REQUESTED** [review]
Looks good otherwise I'd say

**Review by SirYwell — APPROVED** [review]

**Review by dordsor21 — APPROVED** [review]

**Review by MattBDev — APPROVED** [review]
