### PR TITLE
Re-implement full Entity support in history, entity removal, entity creation, etc.

### LINKED ISSUE #676: //undo-ing a paste does not remove copied entities
See title
Using undo after a //paste -e does not remove the entities

### LINKED ISSUE #1596: Entities are not removed when cutting them
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Entities are not removed when using //cut -e

### To Reproduce

1. Place entities, such as armor stands, or villagers
2. Select the area with the entities
3. do //cut -e
4. See how entities remain. When you do //paste -e, the entities will properly be pasted.

### Expected behaviour

The entities should be removed/cut out like the surrounding blocks.

### Screenshots / Videos

**Step 1**

**Step 2&3**

**Step 4**

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/867f3208c8a04ec4831551fa779c95e5

### Fawe Version

FAWE-2.0.2-87

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

[...] He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. [...]

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #1596
 - Fixes #676

### CODE REVIEW

**Review by SirYwell — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/CPUOptimizedClipboard.java [hunk 1]
```diff
@@ -217,6 +219,17 @@ public Entity createEntity(Location location, BaseEntity entity) {
...
 
+    @Nullable
+    @Override
+    public Entity createEntity(Location location, BaseEntity entity, UUID uuid) {
+        Map<String, Tag> map = new HashMap<>(entity.getNbtData().getValue());
+        NBTUtils.addUUIDToMap(map, uuid);
+        entity.setNbtData(new CompoundTag(map));
+        BlockArrayClipboard.ClipboardEntity ret = new BlockArrayClipboard.ClipboardEntity(location, entity);
+        entities.add(ret);
+        return ret;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/CPUOptimizedClipboard.java:230]: For ease of maintainability, how about refactoring this into a protected method? It's the same code in the CPUOP, DOC and MOC.

File: worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java [hunk 2]
```diff
@@ -148,6 +149,20 @@ default Entity createEntity(Location location, BaseEntity entity) {
...
+     * Create an entity at the given location, forcing a UUID onto the entity
+     *
+     * @param entity   the entity
+     * @param location the location
+     * @param uuid     UUID to force the entity to have
+     * @return a reference to the created entity, or null if the entity could not be created
+     * @since TODO
+     */
+    @Nullable
+    @AnnotationHelper.ApiDescription(info = "Only use if you are aware of the consequences of forcing a UUID to an entity.")
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java:162]: [-0.9](https://www.apache.org/foundation/voting.html#expressing-votes-1-0-1-and-fractions) on that one. This is P2 code  and it feels a bit weird to me to use that one here.

**Review by NotMyFault — APPROVED** [review]
