### PR TITLE
fix: adjust linked filter to be left-right and do not link to new forked instances

### LINKED ISSUE #1874: Bad calculation of the number of blocks changed?
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I have currently some problems with max-changed limitation.

I have a rank named 'builder-plus' with 8 millions max-change

```yaml
limits:
[some-line]
  builder-plus:
    # Max actions that can be run concurrently (i.e. commands)
    max-actions: 2
    # Max number of block changes (e.g. by `//set stone`).
    max-changes: 8000000
    # Max number of blocks checked (e.g. `//count stone` which doesn't change blocks)
    max-checks: 80000000
    # Number of times a change can fail (e.g. if the player can't access that region)
    max-fails: 4000000
    # Allowed brush iterations (e.g. `//brush smooth`)
    max-iterations: 500
[some-line]
```

But with `//pos1` `//pos2` and `//set stone` they are limited to 2.5 millions blocks.

I have checked, the permission is well configured, here exemple of luck perms record:
image

### To Reproduce

1. Define limitation
2. Check permission to be limited
3. Try the limitation with simple `//set stone`

### Expected behaviour

I suppose there are complicated to fix this kind of bug.

Many add some step into resolution of this bug : 
As add log or complete the error message with value compared (current max-changed of player and current selection count) ?

### Screenshots / Videos

image

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6e996039991c46ef9176dc2941395c5c

### Fawe Version

FastAsyncWorldEdit-2.4.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Assume that child filters know about their own forks
 - fixes #1874

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java [hunk 1]
```diff
@@ -1,69 +1,102 @@
...
+    public <T extends IChunk> T applyChunk(T chunk, @Nullable Region region) {
+        chunk = getLeft().applyChunk(chunk, region);
+        return getRight().applyChunk(chunk, region);
     }
 
-    public S getChild() {
-        return this.child;
+    @Override
+    public boolean appliesLayer(IChunk chunk, int layer) {
+        return getLeft().appliesLayer(chunk, layer) && getRight().appliesLayer(chunk, layer);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:56]: This should be `||`, shouldn't it?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java [hunk 2]
```diff
@@ -1,69 +1,102 @@
...
+    public boolean appliesChunk(int chunkX, int chunkZ) {
+        return getLeft().appliesChunk(chunkX, chunkZ) && getRight().appliesChunk(chunkX, chunkZ);
     }
 
-    public LinkedFilter(T parent, S child) {
-        super(parent);
-        this.child = child;
+    @Override
+    public <T extends IChunk> T applyChunk(T chunk, @Nullable Region region) {
+        chunk = getLeft().applyChunk(chunk, region);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:50]: `chunk` could be null after the call according to the docs, would it make sense to pass the original value to the right in that case?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java [hunk 3]
```diff
@@ -1,69 +1,102 @@
...
+    public L getLeft() {
+        return this.left;
+    }
+
+    public R getRight() {
+        return this.right;
+    }
+
+    @Override
+    public boolean appliesChunk(int chunkX, int chunkZ) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:44]: Same as for `appliesLayer`

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java (hunk 1 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:56]: I wasn't really sure what was best. Do we want to still filter in one if the other doesn't want to? That implies that edit shouldn't be happening in the layer

Comment (SirYwell) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:56]: My understanding was that the methods basically mean return whether a filter *may* do something with the chunk/layer. Now if we say "right only needs to do something if left did something", then AND should be fine, but otherwise not. There's also a theoretical scenario where right can only decide whether it needs to do something *after* left already did its work. We currently don't have any custom implementations for those methods (the default returns true, other impls just delegate), so maybe it would make sense to just remove them? And if we ever think that something like that might be useful, we can reintroduce it and think about it again, having an actual example at hand.

Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/LinkedFilter.java:56]: Mm that might be the best solution for now, setting the return for applyChunk to nonnull I suppose

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
