### PR TITLE
Fix performance issues getting next file ids

### LINKED ISSUE #887: Clipboard/History/Sessions data causing FAWE to react slowly in a certain dimension (most likely history)
Based on issue #855 

**/fawe debugpaste**: NOTE: Issues #855 and #881 also have debugpastes from the very same server

current debugpaste from the **Paper** Server (where the delay issue still occurs and the history/sessions/clipboard **data is not deleted**: https://athion.net/ISPaster/paste/view/11131ce6d6e84d678abb01c56305530a

current debugpaste from the **Tuinity** Server (server software doesn't play a role in this case, read below) where the history/etc **data IS deleted** and everything works fine again: https://athion.net/ISPaster/paste/view/bec29fe1d1bb4cb481b616d1ea6515da

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 559-585    
- Spigot/Paper Version Number (`/version`): 325-446, also Tuinity 183  
- Minecraft Version: 1.16.5

**Describe the bug**
Two weeks ago, in one dimension, we call it TerraformTest, FAWE had a minimum delay of 2.5+ seconds. Well, we solved it by copying all that progress to our main world dimension, which we were planning to do anyway.

Well, now about two weeks later, that issue doesn't happen on TerraformTest anymore, but on the main world, with a 1 second Minimum delay. 
Fun thing: we moved (cut+paste) the exact same world to another server test environment and all the core plugins (including FAWE), and there was no delay.
We copied it back to the main server environment and after starting, the issue still occured. Although it is a copy of the very same world that had and then didn't have the issue.
Now we made a copy of that world in the main server environment, simply named worldKopie, and after loading it, the issue didn't occur in worldKopie, but continued to appear in world.

Then we deleted world, and renamed worldKopie to world.

The delay issue happened again.

EDIT: We then moved our whole server then to a fresh Tuinity setup, the issue also occured there (we copied over all plugin data, as well as configs and of course, the worlds)

So after testing out a lot of possibilities by starting with using the configs (paper, spigot, bukkit) from the test environment for the main server, I found out something. We already had an idea that it may be something  clogging memory or the I/O thread (got the hint from the myWorlds dev as we first asked whether it could be it, he then recommended Tuinity because it could have also been the lighting engine clogging up), so I looked into the FAWE folder and found out that it is saving a bunch of data per dimension. Hence I just moved in the FAWE folder from the test environment where everything was working fine, and the issue was fixed.

**To Reproduce**
1. Use FAWE for a long while, it will obviously create many "history" files
2. At some point, it will cause FAWE to work slowly and have a minimum time that it needs to do stuff
3. Remove all those files 
4. It will work flawlessly again
5. Extra: If you don't work in this dimension anymore for a while (>1-2 weeks), it will stop happening and work perfectly again (probably because it doesn't create more history files?)

Of course, ask me if you need more info!

**Plugins being used on the server**
See in quoted issue

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by Aurelien30000**
## Overview

This PR aims to fix a huge issue with thousands of history files saved on disk.
The same behavior has been copied out to CfiChangeSet, class that used the same behaviour to get the next file id.

**Fixes #887**

## Description

Firstly, I tried the suggested fix using ``java.nio`` package, that wasn't successful at all.
Then, I decided to simply cache these heavy values in Maps, and load the first value thanks to the old method, still needed with this implementation.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

### CODE REVIEW

File: worldedit-core/src/main/java/com/boydti/fawe/object/changeset/CFIChangeSet.java [hunk 1]
```diff
@@ -11,18 +11,27 @@
 
 import java.io.File;
 import java.io.IOException;
-import java.util.Collections;
-import java.util.Iterator;
-import java.util.UUID;
+import java.util.*;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/boydti/fawe/object/changeset/CFIChangeSet.java:14]: Don't use wildcard imports.

**Review by NotMyFault — CHANGES_REQUESTED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by Aurelien30000** [comment]
Thanks to @SirYwell for the requested changes to improve and ensure safety of this fix!

**Review by SirYwell — APPROVED** [review]
