### PR TITLE
Check cached bukkit player is the same as the current player online

### LINKED ISSUE #1730: World Edit Breaks When Using In Custom Worlds
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Using world edit in a world that is not any of the three main worlds (overworld, nether, end) will cause the plugin to break upon leaving and rejoining.
For example, I teleport to a custom world on the server and set some blocks in any way using FAWE. I then leave the server and rejoin. If I then try to use any FAWE command, nothing will happen and the player will not be able to interact with blocks until rejoining again.
Players cannot use any FAWE command, however, the console can.

A temporary fix I found is deleting the history and clipboard folders and then restarting the server. You would have to repeat this process every time you use world edit and leave the server again.

### To Reproduce

1. Teleport to a custom world.
2. //wand.
3. Select a region and //set stone.
4. Leave the server.
5. Join the server.
6. Use any FAWE command, like //wand.

### Expected behaviour

World edit persists to work across leaving and joining the server despite having history and/or clipboard files saved from a custom world.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/83d37d9ebf5c4949af86eb3ec95898cd

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.1.3-SNAPSHOT-168

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

### PR DESCRIPTION
**Pull request by dordsor21**
- If plugins do silly things like teleport, deop (anything that requires a perm-recheck) (anything that ultimately requires a BukkitPlayer at some point) then the retention of metadata by the server (as it's stored based on a string value indescriminate of player a player relogging) means that a BukkitPlayer caching an old player object will be kept, cached and retrieved by FAWE. Adding a simple memory-based equality check when the player rejoins, and then "invaliding" (redoing) the cache if the players are not equal, fixes this.
 - Fixes #1730

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 1]
```diff
@@ -575,6 +575,14 @@ BukkitPlayer getCachedPlayer(Player player) {
     }
     //FAWE end
```
Comment (NotMyFault) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:576]:
```suggestion
```

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 2]
```diff
@@ -575,6 +575,14 @@ BukkitPlayer getCachedPlayer(Player player) {
...
 
+    public BukkitPlayer reCachePlayer(Player player) {
+        synchronized (player) {
+            BukkitPlayer wePlayer = new BukkitPlayer(this, player);
+            player.setMetadata("WE", new FixedMetadataValue(this, wePlayer));
+            return wePlayer;
+        }
+    }
+
```
Comment (NotMyFault) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:585]:
```suggestion
    //FAWE end
```

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 3]
```diff
@@ -575,6 +575,14 @@ BukkitPlayer getCachedPlayer(Player player) {
     }
     //FAWE end
 
+    public BukkitPlayer reCachePlayer(Player player) {
```
Comment (NotMyFault) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:578]:
```suggestion
   BukkitPlayer reCachePlayer(Player player) {
```
Any objections about shifting the modifier? I don't feel this necessarily needs to be public.

**Review by NotMyFault — APPROVED** [review]

**Review by PierreSchwang — APPROVED** [review]

**Comment by NotMyFault** [comment]
Gonna merge this within the next ~24h

**Review by SirYwell — COMMENTED** [review]
I think this should have a comment in the code why we're doing a reference equality check

**Review by SirYwell — APPROVED** [review]
