### PR TITLE
fix: correctly trim the max chunk section

### LINKED ISSUE #2727: (PlotSquared) Region-Restriction: hight-limit check for FAWE actions not correct
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

The `max_height` setting in the `worlds.yml` of PlotSquared are not used correctly for FAWE actions.

- The `min_height` limitations seems to work.
- But the player can build blocks up to the vanilla world limit (> `max_height` setting)
- `//expand vert` also down't corresponds to the limit settings (> `max_height` setting)
- `/p clear` and `/p confirm` only deletes chunks inside in section **A** (= build limitations of PlotSquared like the setting, see pictures)

#### Test Setup:

```yml
    world:
      min_height: 1
      max_height: 256
      min_gen_height: 0
      max_gen_height: 255
      gamemode: creative
      border_size: 1
      border: false
      component_below_bedrock: false
```

- Testplayer without `plots.admin.build.heightlimit` permission

#### Test Scenario 1:

1. `//expand vert`
2. `//set light_blue_wool`

- **D**: Minecraft Vanilla max-height (Y = -64 - 319)
- **A**: build limitations of PlotSquared like the setting (Y = 1 - 255 ¹ )
- **B**: undefined distance from PS build limit up to **C**
-> _The player should not be able to perform any FAWE actions here! (see test scenario 2)_
- **C**: last chunk before the Minecraft Vanilla max-height
->_The player should not be able to perform any FAWE actions here!_

grafik

¹ = max block hight setting is exclusive
[/Core/src/main/java/com/plotsquared/core/plot/PlotArea.java#L663-L665](https://github.com/RedstoneFuture/PlotSquared/blob/79cc9626750686f03fb6b5d5690bfc6ced9f9569/Core/src/main/java/com/plotsquared/core/plot/PlotArea.java#L663-L665)
```java
    public boolean buildRangeContainsY(int y) {
        return y >= minBuildHeight && y < maxBuildHeight;
    }
```

#### Test Scenario 2:

1. `//pos1` & `//pos2` partial within **D**
2. `//set light_blue_wool`

It always cuts the actions slightly downwards. But one part always remains. (It's not a visual bug.)

grafik

### Expected behaviour

The player should not be able to perform any FAWE actions in section **B** and **C**.

### Screenshots / Videos

https://redstoneworld.de/videos/intern/FAWE_Height-limit-check.mp4

### Error log (if applicable)

- no errors, no warns

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/643ae3b115794143b6acff5748f77a98

### Fawe Version

FAWE Bukkit - build 659 and build 764

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

- tested with PlotSquared `7.3.9`

### PR DESCRIPTION
**Pull request by dordsor21**
- fixes #2727
 - fixes IntellectualSites/Plotsquared#4436

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java [hunk 1]
```diff
@@ -828,8 +828,10 @@ public IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet set) {
                 return set;
             }
 
-            for (int layer = get.getMinSectionPosition(); layer < get.getMaxSectionPosition(); layer++) {
+            for (int layer = get.getMinSectionPosition(); layer <= get.getMaxSectionPosition(); layer++) {
+                System.out.println(layer);
                 if (!set.hasSection(layer)) {
+                    System.out.println("n " + layer);
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java:834]: n

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java [hunk 2]
```diff
@@ -828,8 +828,10 @@ public IChunkSet processSet(IChunk chunk, IChunkGet get, IChunkSet set) {
                 return set;
             }
 
-            for (int layer = get.getMinSectionPosition(); layer < get.getMaxSectionPosition(); layer++) {
+            for (int layer = get.getMinSectionPosition(); layer <= get.getMaxSectionPosition(); layer++) {
+                System.out.println(layer);
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java:832]: not n

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

File: worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java [hunk 3]
```diff
@@ -174,22 +173,21 @@ public FaweMask getMask(Player player, MaskType type, boolean isWhitelist, boole
...
-            int min = area != null ? area.getMinBuildHeight() : world.getMinY();
-            // PlotSquared uses exclusive max height, WorldEdit uses inclusive max height -> subtract 1
-            int max = area != null ? Math.min(world.getMaxY(), area.getMaxBuildHeight() - 1) : world.getMaxY();
 
             final CuboidRegion region = regions.iterator().next();
             final BlockVector3 pos1 = BlockVector3.at(region.getMinimumX(), min, region.getMinimumZ());
             final BlockVector3 pos2 = BlockVector3.at(region.getMaximumX(), max, region.getMaximumZ());
             maskedRegion = new CuboidRegion(pos1, pos2);
         } else {
-            World world = FaweAPI.getWorld(area.getWorldName());
```
Comment (PierreSchwang) [inline worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java:189]: Is there any specific reason why the world was obtained by the area directly, instead of the players current world? (As the world variable was combined to just the users world in L176)

Comment (dordsor21) [reply worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/regions/plotsquared/PlotSquaredFeature.java:189]: I couldn't see any reason for that tbh, possibly left over from a long time ago?

**Review by PierreSchwang — APPROVED** [review]
