### PR TITLE
fix: apply origin to sponge v3 schematics

### LINKED ISSUE #2864: Schematics dont remember their positions
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When you load a schematic on 1.21 and then paste it using //paste -o, the schematic forgets its position and gets pasted to 0, 0, 0.

### To Reproduce

1. Launch the server on 1.21
2. Select & copy an area -> //copy
3. Save the area as a schematic -> //schem save
4. Load the schematic using -> //schem load
5. Type //paste -o -> it will get pasted at 0, 0, 0

### Expected behaviour

Schematics should remember their positions, just like clipboard.

### Screenshots / Videos

https://github.com/user-attachments/assets/a1ff1693-3c18-4a6f-89e2-eb7b28261363

### Error log (if applicable)

_No response_

### Fawe Debugpaste

Can give in Discord DMs

### Fawe Version

2.11.1-SNAPSHOT-865;638344d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MidSpike**
## Overview
Fixes #2864

## Description
- Applies the set origin in v3 schematics when loading using the fast implementation
- Applies upstream fix for WorldEdit v3 reader https://github.com/EngineHub/WorldEdit/commit/cfd9eeabae14a062bb53dd931e4ec9c6e9be89fb

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java [hunk 1]
```diff
@@ -136,6 +139,27 @@ public Clipboard read(final UUID uuid, final Function<BlockVector3, Clipboard> c
                     this.dataVersion = this.dataInputStream.readInt();
                     this.dataFixer = ReaderUtil.getVersionedDataFixer(this.dataVersion, platform, platform.getDataVersion());
                 }
+                case "Metadata" -> {
+                    LinCompoundTag metadataCompoundTag =
+                            (LinCompoundTag) this.nbtInputStream.readTagPayload(NBTConstants.TYPE_COMPOUND, 2).toLinTag();
+
+                    LinCompoundTag worldEditTag = metadataCompoundTag.findTag("WorldEdit", LinTagType.compoundTag());
+                    if (worldEditTag == null) {
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:147]: Schematic's don't need to contain a WorldEdit compound in the metadata. Everything under metadata should be optional.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java [hunk 2]
```diff
@@ -136,6 +139,27 @@ public Clipboard read(final UUID uuid, final Function<BlockVector3, Clipboard> c
                     this.dataVersion = this.dataInputStream.readInt();
                     this.dataFixer = ReaderUtil.getVersionedDataFixer(this.dataVersion, platform, platform.getDataVersion());
                 }
+                case "Metadata" -> {
+                    LinCompoundTag metadataCompoundTag =
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:143]: I would prefer the data here to be read in a similar way like the other parts of the reader. So, not reading a whole compound in memory but streaming over the tags - especially as the metadata might be huge, depending where the schematic was generated.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java [hunk 3]
```diff
@@ -87,6 +89,7 @@ public class FastSchematicReaderV3 implements ClipboardReader {
 
     private VersionedDataFixer dataFixer;
     private BlockVector3 offset;
+    private BlockVector3 origin;
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:92]: should default to `BlockVector3.DEFAULT` (see the other comment for reason)

**Review by PierreSchwang — CHANGES_REQUESTED** [review]
Seems to work so far otherwise, I'd say.

You can cherrypick https://github.com/EngineHub/WorldEdit/commit/cfd9eeabae14a062bb53dd931e4ec9c6e9be89fb into here as well, theoretically.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java (hunk 3 above)
Comment (MidSpike) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java]: Implemented default value

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java (hunk 1 above)
Comment (MidSpike) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java]: Implemented ability for metadata sub-tags to be optional

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java (hunk 2 above)
Comment (MidSpike) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:143]: @PierreSchwang Unfortunately, I had already made an attempt to preserve the performance oriented goals of the stream reading. As it turns out, I am lacking in familiarity on a more consist approach, hence my hasted attempt to get it working properly.

Any help would be appreciated!

**Comment by PierreSchwang** [comment]
I guess I'm okay with reading the whole tag, I don't expect the metadata to be that large. Could you please apply the correct PR template? It seems you deleted it

**Comment by MidSpike** [comment]
> I guess I'm okay with reading the whole tag, I don't expect the metadata to be that large. Could you please apply the correct PR template? It seems you deleted it

@PierreSchwang I'm unable to find a way to retroactively apply a PR template (and copy-pasting from a different PR doesn't seem to format properly).

**Comment by PierreSchwang** [comment]
> > I guess I'm okay with reading the whole tag, I don't expect the metadata to be that large. Could you please apply the correct PR template? It seems you deleted it
> 
> @PierreSchwang I'm unable to find a way to retroactively apply a PR template (and copy-pasting from a different PR doesn't seem to format properly).

I edited to my best - you may adjust

**Comment by MidSpike** [comment]
@PierreSchwang all good from me unless you need anything else changed.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java [hunk 4]
```diff
@@ -136,6 +139,24 @@ public Clipboard read(final UUID uuid, final Function<BlockVector3, Clipboard> c
                     this.dataVersion = this.dataInputStream.readInt();
                     this.dataFixer = ReaderUtil.getVersionedDataFixer(this.dataVersion, platform, platform.getDataVersion());
                 }
+                case "Metadata" -> {
+                    LinCompoundTag metadataCompoundTag =
+                            (LinCompoundTag) this.nbtInputStream.readTagPayload(NBTConstants.TYPE_COMPOUND, 2).toLinTag();
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:144]: Any specific reason using 2 as the initial depth over 0?

**Review by PierreSchwang — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java (hunk 4 above)
Comment (MidSpike) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/io/FastSchematicReaderV3.java:144]: I'll be honest, that is left-over from when I was familiarizing myself with the codebase.
Let me push a commit real quick to change that to `0` (tested and working).

**Review by dordsor21 — APPROVED** [review]

**Comment by PierreSchwang** [comment]
Thank you!
