### PR TITLE
fix: fixed history rollback

### LINKED ISSUE #2366: Extreme freakout when rolling back history
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I inputted the command //history rollback -u (username hidden for privacy) -r 50 -t 12h and the server began to create odd chunks *everywhere* around the area.

All of this goes underground and overground. It eventually crashed the server. The log for this is below.
[2023-07-18-2.log.gz](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/12089053/2023-07-18-2.log.gz)

### To Reproduce

//history rollback -u (username hidden for privacy) -r 50 -t 12h

//confirm

Watch your server crash.

### Expected behaviour

Roll back worldedits. Not... destroy everything.

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/032b2e4cae1543bebc6defc88a2a9715

### Fawe Version

2.6.5-SNAPSHOT-522;a680c7c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Actual issue is setting the editsession changeset to the changeset we're undoing...?!?! And so we start arbitrarily overriding the history we want to save and completely and utterly fucking everything. Please let's not do that again. Thanks :)
 - Also go ahead and clean up other parts of this, with more appropriate operators used
 - Fixes #2366

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java [hunk 1]
```diff
@@ -230,6 +233,7 @@ public void flush() {
     public void close() throws IOException {
         super.close();
         synchronized (this) {
+            System.out.println("CLOSING");
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java:236]: Leftover?

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java [hunk 2]
```diff
@@ -131,7 +131,7 @@ public synchronized void rollback(
             other = null;
         }
         Location origin = player.getLocation();
-        BlockVector3 bot = origin.toBlockPoint().subtract(radius, radius, radius);
+        BlockVector3 bot  = origin.toBlockPoint().subtract(radius, radius, radius);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java:134]:
```suggestion
        BlockVector3 bot = origin.toBlockPoint().subtract(radius, radius, radius);
```

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java [hunk 3]
```diff
@@ -159,14 +159,11 @@ public Iterable<Supplier<RollbackOptimizedHistory>> getEdits(
...
                 int count = 0;
-                String stmtStr = ascending ? uuid == null ? "SELECT * FROM`" + this.prefix + "edits` WHERE `time`>? AND `x2`>=? AND" +
-                        " `x1`<=? AND `z2`>=? AND `z1`<=? AND `y2`>=? AND `y1`<=? ORDER BY `time` , `id`" :
-                        "SELECT * FROM`" + this.prefix + "edits` WHERE `time`>? AND" +
-                                " `x2`>=? AND `x1`<=? AND `z2`>=? AND `z1`<=? AND `y2`>=? AND `y1`<=? AND `player`=? ORDER BY `time` ASC, `id` ASC" :
-                        uuid == null ? "SELECT * FROM`" + this.prefix + "edits` WHERE `time`>? AND `x2`>=? AND `x1`<=? AND `z2`>=? " +
-                                "AND `z1`<=? AND `y2`>=? AND `y1`<=? ORDER BY `time` DESC, `id` DESC" :
-                                "SELECT * FROM`" + this.prefix + "edits` WHERE `time`>? AND `x2`>=? AND `x1`<=? AND" +
-                                        " `z2`>=? AND `z1`<=? AND `y2`>=? AND `y1`<=? AND `player`=? ORDER BY `time` DESC, `id` DESC";
+                String stmtStr = ascending
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java:162]: Can we use if-else here and probably also text blocks?

**Review by SirYwell — CHANGES_REQUESTED** [review]

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
