### PR TITLE
fix: anglecolor

### LINKED ISSUE #3032: #anglecolor not working
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

When using //replace #anglecolor[5] an error shows up, I've already put the 1.21.1 jar in the textures/ folder.

### To Reproduce

0. Put the 1.21.1 jar in the textures/ folder
1. Select some blocks
2. Run //replace #anglecolor[5]
3. Error thrown

### Expected behaviour

The command should work properly

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/007212582fc8490f85c624ad4af49926

### Fawe Version

FastAsyncWorldEdit version 2.12.3-SNAPSHOT-996;7427665

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #3032

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java [hunk 1]
```diff
@@ -409,6 +409,11 @@ public BiomeType getBiomeType(int x, int y, int z) {
         return getExtent().getBiomeType(x, y, z);
     }
 
+    @Override
+    public BiomeType getBiome(final BlockVector3 position) {
```
Comment (dordsor21) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java:413]: Are there potentially other places we need to add the override/load?

Comment (PierreSchwang) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java:413]: Haven't seen any other occurrences in implementations, which would need that. I could've potentially implemented that in FilterBlock.java - but that could result in a Stackoverflow, if getBiomeType / getBiome is not properly implemented (due to getBiomeType maybe delegating to getBiome, which defaults to getBiomeType)

Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/filter/block/CharFilterBlock.java:413]: Okay cool, LGTM

**Review by dordsor21 — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]
