### PR TITLE
Fix vault, remove 1.14 and DummyFawe

### LINKED ISSUE #516: FAWE-WorldGuard entry problem
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/744df028260b42b5817fe71b5ec1b7ad

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
------------------ Platforms ------------------
* Bukkit-Official(1.15-263;3d40336)
>.... [13:56:14 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-365 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
When trying to enter a region with limited members-only entry (provided by WorldGuard), I get blocked even though I have the proper permissions.
This may seem a problem with WorldGuard, **BUT** the problem does **not** consist when switching to regular WorldEdit.

**How to replicate**:
Create a region with WorldGuard, set entry to members only, add a group as a member, make sure you are in that group (or have the permission), try to enter - you can't.

**Plugins being used on the server:**
Unnecessary - problem does **not** consist when switching back to regular WorldEdit.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

### LINKED ISSUE #529: TogglePermission (I.e. /wea & /tips) Non-Functional
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/a8644755030b423eb10c9dea7d919f6a
(Small Test Server w/ Minimal Plugins)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
 Bukkit-Official(1.16-293;6d6de61)

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-353 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**
`togglePermission` (as in /wea and /tips) seems to be broken, currently (Currently tested on `Bukkit-Official(1.16-293;6d6de61)`). 
Instead of toggling and returning the new state (as in the `Subject` interface), it's just returning the current state of the perm.
```java
@Override public boolean togglePermission(String permission) {
    return permActor.hasPermission(permission);
}
```
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlayerProxy.java#L178-L180

**How to replicate**:

Running `/wea` with `fawe.admin` will constantly report that your changes are now restricted.
With `fawe.bypass` It'll report that you're now bypassing. No perm changes are performed.

**Plugins being used on the server:**
- FAWE
- LuckPerms
- Vault

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by IronApollo**
## Overview
This PR fixes the group issues FAWE had when paired with WorldGuard. By fixing the way we initialize our plugin, we ensure the Vault plugin has time to load and provide the proper values back to FAWE.

This PR also removes the need for DummyFawe by utilizing the "provides" plugin.yml attribute. A check has been added to encourage users to remove DummyFawe. This will also reduce the upstream occurrences of users seeking help with WorldEdit issues where the root if the issue is the lingering DummyFawe plugin.

**Fixes #516 , Possibly Fixes #529**

## Checklist
- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java [hunk 1]
```diff
@@ -240,13 +241,15 @@ public void setPermission(String permission, boolean value) {
          *  Permissions are used to managing WorldEdit region restrictions
          *   - The `/wea` command will give/remove the required bypass permission
          */
-        if (Fawe.<FaweBukkit>imp().getVault() == null || Fawe.<FaweBukkit> imp().getVault().permission == null) {
-            player.addAttachment(plugin).setPermission(permission, value);
-        } else if (value) {
-            if (!Fawe.<FaweBukkit> imp().getVault().permission.playerAdd(player, permission)) {
+        if(VaultResolver.perms != null){
```
Comment (N0tMyFaultOG) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitPlayer.java:244]:
```java
if (VaultResolver.perms != null) {
```
etc.
Checkstyle please

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 2]
```diff
@@ -204,18 +133,23 @@ public void onLoad() {
             ChunkDeleter.runFromFile(delChunks, true);
         }
 
-        fail(() -> PermissionsResolverManager.initialize(INSTANCE), "Failed to initialize permissions resolver");
+        if(this.getDataFolder().getParentFile().listFiles(file -> {
```
Comment (N0tMyFaultOG) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:136]:
```java
if (this.getDataFolder().getParentFile().listFiles(file -> {
```
etc

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 3]
```diff
@@ -204,18 +133,23 @@ public void onLoad() {
...
+            if(file.getName().equals("DummyFawe.jar")){
+                return true;
+            }
+            return false;
+        }).length > 0){
+            getLogger().warning("DummyFawe detected! This is no longer necessary. Please remove immediately and restart your server!");
```
Comment (N0tMyFaultOG) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:142]: We could just delete the file here notifying the jar has been deleted. The chance people check their logs looking for issues is pretty low.
If DummyFawe is present, it will trigger `Ambiguous plugin name...` anyway since the name is the same.

**Review by N0tMyFaultOG — CHANGES_REQUESTED** [review]

**Comment by dordsor21** [comment]
DummyFAWE should remain in use for 1.14 versions as they won't have the provides feature.

**Comment by IronApollo** [comment]
I believe this PR is finished and has met all requested changes. I don't think DummyFawe should continue to exist, even if it means the current latest FAWE release will be the last for 1.14. Focusing on consistency and working forward is more important to me than creating workarounds for old versions. If anyone would like to push a commit for that feature, feel free but this PR is done in terms of my contributions!

**Review by MattBDev — APPROVED** [review]

File: worldedit-bukkit/src/main/resources/plugin.yml [hunk 4]
```diff
@@ -1,9 +1,10 @@
-name: WorldEdit
+name: FastAsyncWorldEdit
 main: com.sk89q.worldedit.bukkit.WorldEditPlugin
 version: "${internalVersion}"
 load: STARTUP
 api-version: 1.13
```
Comment (N0tMyFaultOG) [inline worldedit-bukkit/src/main/resources/plugin.yml:5]: The `api-version` should adjusted to 1.15 here, as it doesn't support versions prior to.

**Review by N0tMyFaultOG — CHANGES_REQUESTED** [review]

**Comment by N0tMyFaultOG** [comment]
If we are going to strip 1.14, this should be done in this pr as well

**Review by N0tMyFaultOG — APPROVED** [review]

**Review by MattBDev — APPROVED** [review]
