### PR TITLE
Fix relight and removelight

### LINKED ISSUE #459: Broken lighting when using WorldEdit operations.
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config: https://paste.ubuntu.com/p/9hDB8hdgSM/
config-legacy: https://paste.ubuntu.com/p/MkQDTRFwNw/

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit dev 217

**[REQUIRED] Spigot/Paper Version Number:** 
Paper dev 273 (Spigot 1.15.2)

**[REQUIRED] Description of the problem:**
Chunk relighting is broken when doing worldedit operations.

**How to replicate**:
* Make a 2 point selection.
* //replace air

link
link

Also tested with these changes.

```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: true
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 1
  # If existing lighting should be removed before relighting
  remove-first: false
```
```
lighting:
  # If packet sending should be delayed until relight is finished
  delay-packet-sending: false
  async: true
  # The relighting mode to use:
  #  - 0 = None (Do no relighting)
  #  - 1 = Optimal (Relight changed light sources and changed blocks)
  #  - 2 = All (Slowly relight every blocks)
  mode: 2
  # If existing lighting should be removed before relighting
  remove-first: true
```
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by dordsor21**
Automagic lighting when doing the edit can be something that is done later.
Fixes #459

### CODE REVIEW

**Comment by aurorasmiles** [comment]
fixes #459

**Comment by aurorasmiles** [comment]
fixes #314 (which is a duplicate of 459 i guess but nvm)

**Comment by IronApollo** [comment]
You've done great work on this! So happy to see such an important feature reimplemented.

How's performance looking with this?

**Comment by dordsor21** [comment]
Cheers. Seems alright? It shouldn't be any better or worse than it used to be (other than the fact 1.13+ performance is plain bad). The switch from queue to chunk shouldn't make a difference as the same chunks had to be loaded in 1.12 anyway.

File: worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/NMSRelighter.java [hunk 1]
```diff
@@ -0,0 +1,637 @@
...
+            iter.remove();
+        }
+    }
+
+    public void updateBlockLight(Map<Long, long[][][]> map) {
+        int size = map.size();
+        if (size == 0) {
+            return;
+        }
+        Queue<MutableBlockVector3> lightPropagationQueue = new ArrayDeque<>();
```
Comment (Sauilitired) [inline worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/NMSRelighter.java:158]: Consider allocating these with a reasonable initial capacity to prevent it from being expanded when new items are added because speed and stuff

File: worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/NMSRelighter.java [hunk 2]
```diff
@@ -0,0 +1,637 @@
...
+    }
+
+    @Override
+    public synchronized void removeAndRelight(boolean sky) {
+        removeFirst = true;
+        fixLightingSafe(sky);
+        removeFirst = false;
+    }
+
+    private void set(int x, int y, int z, long[][][] map) {
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/NMSRelighter.java:67]: A vague method with the name "set" should have a comment before it explaining what the method does because it isn't clear what is being set.

File: worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/Relighter.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    void clear();
+
+    void removeLighting();
+
+    void fixBlockLighting();
+
+    void fixSkyLighting();
+
+    boolean isEmpty();
+
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/lighting/Relighter.java:24]: Methods such as `addChunk()` and `fixLightingSafe()` should have documentation.

File: worldedit-core/src/main/java/com/boydti/fawe/object/RelightMode.java [hunk 4]
```diff
@@ -0,0 +1,7 @@
+package com.boydti.fawe.object;
+
+public enum RelightMode {
+    NONE,
+    OPTIMAL,
+    ALL
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/boydti/fawe/object/RelightMode.java:6]: There should be a comment here describing the differences between OPTIMAL and ALL. Anyone using the code in the future should know what OPTIMAL actually means.

**Comment by Doxturtle** [comment]
Hi, got these errors whilst using the lighting fix on 1.14.4 paper.

I was using //replace to remove acacia trees in my world, after doing this my server crashed. When attempting to fix lighting in the removed areas I was getting these errors. I tried varying selection sizes and it seemed to make some difference, but it wasn't entirely an entirely consistent pattern. 

https://pastebin.com/ZY5NUHNi

When fixing the lighting it was also causing weird artefacts like the interior of trees to become very dark and underwater lighting to be no longer dark.

**Comment by aurorasmiles** [comment]
Don't exactly know what I was doing, just messing around, and got this error
http://haste.athion.net/ulilijamap.bash

**Comment by aurorasmiles** [comment]
Apparently using //removelight and then //fixlight in the same section produces that issue

**Comment by aurorasmiles** [comment]
Found a few issues still, mostly with half blocks
https://drop.cutiepie.at/xm5mt62ceqwegydu
https://drop.cutiepie.at/v920uzisn5wbg13b

**Comment by dordsor21** [comment]
Issues with slabs etc are present in 1.12 lighting. At this point, I think it's acceptable to bring the behaviour to what it was in 1.12 before worrying too much about complete fixes
