### PR TITLE
Re-implement richer mask and transform parsing

### LINKED ISSUE #509: Using multiple masks within the same command doesn't work.
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/10377e8dfc2f4c0c833243f614ff2e03

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
* Bukkit-Official(1.15-260;33c3cb2) 

**[REQUIRED] Spigot/Paper Version Number:** 
The server is running Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) 
Checking version, please wait…
Previous version: git-Paper-277 (MC 1.15.2)
You are running the latest version

**[REQUIRED] Description of the problem:**
using multiple masks within the same command doesn’t work. When trying to use use a mask such as 0&[>2] which masks air and above grass, it returns an invalid input message: 

(FAWE) Invalid value for [maskOpt] (No match for '0&[>2]) acceptable values are any mask. 

Making you unable to use different masks within the same command and only way to bypass this is  ( using 2 masks maximum) is to use a normal brush mask for the 1st mask and a gmask for the 2nd.
Using comma's instead of brackets does not change the outcome/result. 

**How to replicate**:
/br sphere 35:14 2 
/mask 0&[>2]
(or other combinations such as:)
/mask 0&[~98]

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

### LINKED ISSUE #595: #darken and #lighten are not recognized as patterns.
# Bug report for FastAsyncWorldEdit 1.16.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/e600cc926acb4179b6845a07416b1964

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-328

**[REQUIRED] Spigot/Paper Version Number:** 
git-paper-173 (MC 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Trying to equip a brush with the command /brush sphere #darken 10 or /brush sphere #lighten 10
I get the following output: 
https://i.imgur.com/jI56fkP.png 
https://i.imgur.com/Zq6aYSy.png

**How to replicate**:
Use the #darken or #lighten pattern on any command that uses a pattern as an argument, for example /brush sphere #darken 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by dordsor21**
- Reimplementation of //gtransform (#693)
- Re-add richer mask parsing (allow [stone&<grass_block],dirt) etc
- Fixes #509 
- Fixes #595 
- Fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1008

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java [hunk 1]
```diff
@@ -1,189 +1,218 @@
...
+                } else if (!worldEdit.getMaskFactory().containsAlias(command)) {
+                    // Legacy patterns
+                    char char0 = command.charAt(0);
+                    boolean charMask = input.length() > 1 && input.charAt(1) != '[';
+                    if (charMask && input.charAt(0) == '=') {
+                        return parseFromInput(char0 + "[" + input.substring(1) + "]", context);
+                    }
+                    if (char0 == '#') {
+                        throw new SuggestInputParseException(
+                                new NoMatchException("Unknown mask: " + full + ", See: //masks"),
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java:78]: Deprecated in favor of components. Please create a translation message. Also, the latter is not a command. (Afaik) you can't list masks ingame at the moment. That used to be legacy-like behavior.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java [hunk 2]
```diff
@@ -1,189 +1,218 @@
...
+                                            String[] splitSuggestion = suggestion.split(" ");
+                                            suggestion = "[" + StringMan.join(splitSuggestion, "][") + "]";
+                                            result.set(i, suggestion);
+                                        }
+                                    }
+                                }
+                                return result;
+                            } catch (Throwable e2) {
+                                e2.printStackTrace();
+                                throw new InputParseException(e2.getMessage());
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java:185]: Deprecated in favor of components

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java [hunk 3]
```diff
@@ -1,189 +1,218 @@
...
+                if (pe.isAnd()) {
+                    masks.add(new ArrayList<>());
+                }
+                masks.get(masks.size() - 1).add(mask);
+            }
+        } catch (InputParseException rethrow) {
+            throw rethrow;
+        } catch (Throwable e) {
+            e.printStackTrace();
+            throw new InputParseException(e.getMessage(), e);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java:199]: Deprecated in favor of components

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java [hunk 4]
```diff
@@ -1,189 +1,218 @@
...
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
+
+public class DefaultMaskParser extends FaweParser<Mask> {
+
+    public DefaultMaskParser(WorldEdit worldEdit) {
+        super(worldEdit);
+    }
+
+    @Override
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/mask/DefaultMaskParser.java:38]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+import java.util.Locale;
+import java.util.Map;
+
+public class DefaultTransformParser extends FaweParser<ResettableExtent> {
+
+    public DefaultTransformParser(WorldEdit worldEdit) {
+        super(worldEdit);
+    }
+
+    @Override
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:29]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+        Actor actor = context != null ? context.getActor() : null;
+        if (actor != null) {
+            locals.put(Actor.class, actor);
+        }
+        try {
+            List<Map.Entry<ParseEntry, List<String>>> parsed = parse(input);
+            for (Map.Entry<ParseEntry, List<String>> entry : parsed) {
+                ParseEntry pe = entry.getKey();
+                String command = pe.getInput();
+                ResettableExtent transform = null;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:50]: The initializer appears to be redundant

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+                        command = command.substring(percentIndex + 1);
+                        if (!entry.getValue().isEmpty()) {
+                            if (!command.isEmpty()) {
+                                command += " ";
+                            }
+                            command += StringMan.join(entry.getValue(), " ");
+                        }
+                        transform = parseFromInput(command, context);
+                    } else {
+                        throw new NoMatchException("See: //transforms");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:68]: Deprecated in favor of components. That is not a command either. See my comment on `//masks`.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+                    }
+                } else {
+                    try {
+                        transform = worldEdit.getTransformFactory().parseWithoutDefault(pe.getFull(), context);
+                    } catch (SuggestInputParseException rethrow) {
+                        throw rethrow;
+                    } catch (Throwable e) {
+                        throw new NoMatchException("See: //transforms");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:76]: See former comment

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+                    }
+                }
+                if (pe.isAnd()) { // &
+                    intersectionChances.add(chance);
+                    intersection.add(transform);
+                } else {
+                    if (!intersection.isEmpty()) {
+                        if (intersection.size() == 1) {
+                            throw new InputParseException("Error, floating &");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:85]: Deprecated in favor of components

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+                    unionChances.add(chance);
+                    union.add(transform);
+                }
+            }
+        } catch (Throwable e) {
+            throw new InputParseException(e.getMessage(), e);
+        }
+        if (!intersection.isEmpty()) {
+            if (intersection.size() == 1) {
+                throw new InputParseException("Error, floating &");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:108]: Deprecated in favor of components

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java [hunk 11]
```diff
@@ -0,0 +1,136 @@
...
+                total += value;
+                multi.add(intersection.get(i), value);
+            }
+            union.add(multi);
+            unionChances.add(total);
+            intersection.clear();
+            intersectionChances.clear();
+        }
+        if (union.isEmpty()) {
+            throw new NoMatchException("See: //transforms");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/DefaultTransformParser.java:123]: See previous comment

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/Linear3DTransformParser.java [hunk 12]
```diff
@@ -0,0 +1,45 @@
...
+    @Override
+    protected ResettableExtent parseFromInput(@NotNull String[] arguments, ParserContext context) throws InputParseException {
+        if (arguments.length != 1) {
+            return null;
+        }
+        ResettableExtent inner = worldEdit.getTransformFactory().parseFromInput(arguments[0], context);
+        if (inner instanceof RandomTransform) {
+            return new Linear3DTransform(((RandomTransform) inner).getExtents().toArray(new ResettableExtent[0]));
+        }
+        return inner; // TODO what about non-random transforms?
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/Linear3DTransformParser.java:42]: 👀

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java [hunk 13]
```diff
@@ -0,0 +1,58 @@
...
+import com.sk89q.worldedit.extension.input.InputParseException;
+import com.sk89q.worldedit.extension.input.ParserContext;
+import com.sk89q.worldedit.internal.registry.InputParser;
+
+import java.util.List;
+import java.util.stream.Stream;
+
+public class RandomTransformParser extends InputParser<ResettableExtent> {
+
+    public RandomTransformParser(WorldEdit worldEdit) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java:16]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ResettableExtent.java [hunk 14]
```diff
@@ -38,7 +39,7 @@ public ResettableExtent setExtent(Extent extent) {
                 && next instanceof ResettableExtent) {
             ((ResettableExtent) next).setExtent(extent);
         } else {
-            new ExtentTraverser(this).setNext(new AbstractDelegateExtent(extent));
+            new ExtentTraverser(this).setNext(extent);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/ResettableExtent.java:42]: ExtentTraverser takes a generic

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/ScaleTransform.java [hunk 15]
```diff
@@ -19,23 +19,25 @@
     private final double dy;
     private final double dz;
     private transient MutableBlockVector3 mutable = new MutableBlockVector3();
+    private transient int minY;
     private transient int maxy;
     private transient BlockVector3 min;
 
-
     public ScaleTransform(Extent parent, double dx, double dy, double dz) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/transform/ScaleTransform.java:26]: Javadocs

File: worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java [hunk 16]
```diff
@@ -240,6 +242,10 @@ public PatternFactory getPatternFactory() {
         return patternFactory;
     }
 
+    public TransformFactory getTransformFactory() {
+        return transformFactory;
+    }
+
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/WorldEdit.java:248]: Javadocs & Fawe annotations

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java [hunk 17]
```diff
@@ -360,33 +361,33 @@ public void smask(
...
+                          @Switch(name = 'h', desc = "Whether the offhand should be considered or not")
+                                  boolean offHand,
+                          Arguments arguments) throws WorldEditException {
+        BrushTool tool = session.getBrushTool(player, false);
+        if (tool == null) {
+            player.print(Caption.of("fawe.worldedit.brush.brush.none"));
+            return;
+        }
+        if (transform == null) {
+            player.print(Caption.of("fawe.worldedit.brush.brush.transform.disabled"));
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/ToolUtilCommands.java:381]: There's no caption for that string.

File: worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java [hunk 18]
```diff
@@ -840,7 +840,7 @@ private void printUsage(Actor actor, List<String> arguments) {
     //FAWE end
 
     //FAWE start - Event & suggestions
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/extension/platform/PlatformCommandManager.java:842]: Update annotation

File: worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java [hunk 19]
```diff
@@ -405,6 +405,14 @@ default boolean contains(BlockVector3 pt) {
         return pt.containedWithin(min, max);
     }
 
+    default boolean contains(int x, int y, int z) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/extent/Extent.java:408]: Javadocs

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java [hunk 20]
```diff
@@ -101,4 +103,13 @@ public void register(InputParser<E> inputParser) {
         parsers.add(parsers.size() - 1, inputParser);
     }
 
+    public boolean containsAlias(String alias) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/AbstractFactory.java:106]: Javadocs

**Review by NotMyFault — CHANGES_REQUESTED** [review]
Idk whether I used this within this properly, at least it did something https://paste.gg/p/anonymous/906c33d0c0324b13ae66a1c69c0960c7

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/TransformFactory.java [hunk 21]
```diff
@@ -0,0 +1,146 @@
...
+        List<ResettableExtent> ResettableExtents = new ArrayList<>();
+
+        for (String component : input.split(" ")) {
+            if (component.isEmpty()) {
+                continue;
+            }
+
+            ResettableExtent match = null;
+
+            parseFromParsers(context, ResettableExtents, component, match);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/TransformFactory.java:111]: That could be inlined with `null`.

File: worldedit-core/src/main/resources/lang/strings.json [hunk 22]
```diff
@@ -135,6 +136,9 @@
     "fawe.error.input-parser-exception": "Invalid empty string instead of boolean.",
     "fawe.error.invalid-boolean": "Invalid boolean {0}",
     "fawe.error.schematic.not.found": "Schematic {0} not found.",
+    "fawe.error.parse.invalid-dangling-character": "Invalid dangling character {0}.",
+    "fawe.error.parse.unknown-mask": "Unknown mask: {0}, See: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Masks",
+    "fawe.error.parse.unknown-transform": "Unknown transform: {0}, See: https://github.com/IntellectualSites/FastAsyncWorldEdit-Documentation/wiki/Transforms",
```
Comment (NotMyFault) [inline worldedit-core/src/main/resources/lang/strings.json:141]: Parse links within code. If we update them at any time for any reason, existing translations do not update. Putting this here for both, put that in a ClickEvent#openUrl. That is more convenient, else people cannot click links.

**Review by NotMyFault — CHANGES_REQUESTED** [review]

**Review by NotMyFault — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/DarkenPatternParser.java [hunk 23]
```diff
@@ -0,0 +1,31 @@
...
+import com.sk89q.worldedit.internal.registry.SimpleInputParser;
+
+import java.util.Collections;
+import java.util.List;
+
+public class DarkenPatternParser extends SimpleInputParser<Pattern> {
+
+    private final List<String> aliases = Collections.singletonList("#darken");
+
+    public DarkenPatternParser(WorldEdit worldEdit) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/DarkenPatternParser.java:17]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/ExpressionPatternParser.java [hunk 24]
```diff
@@ -0,0 +1,48 @@
...
+import com.sk89q.worldedit.util.formatting.text.TextComponent;
+
+import java.util.Collections;
+import java.util.List;
+
+public class ExpressionPatternParser extends SimpleInputParser<Pattern> {
+
+    private final List<String> aliases = Collections.singletonList("=");
+
+    public ExpressionPatternParser(WorldEdit worldEdit) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/ExpressionPatternParser.java:23]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/LightenPatternParser.java [hunk 25]
```diff
@@ -0,0 +1,31 @@
...
+import com.sk89q.worldedit.internal.registry.SimpleInputParser;
+
+import java.util.Collections;
+import java.util.List;
+
+public class LightenPatternParser extends SimpleInputParser<Pattern> {
+
+    private final List<String> aliases = Collections.singletonList("#lighten");
+
+    public LightenPatternParser(WorldEdit worldEdit) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/LightenPatternParser.java:17]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoXPatternParser.java [hunk 26]
```diff
@@ -0,0 +1,46 @@
...
+
+public class NoXPatternParser extends RichParser<Pattern> {
+
+    /**
+     * Create a new rich parser with a defined prefix for the result, e.g. {@code #simplex}.
+     *
+     * @param worldEdit the worldedit instance.
+     */
+    public NoXPatternParser(WorldEdit worldEdit) {
+        super(worldEdit, "#!x", "#nx", "#nox");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoXPatternParser.java:23]: Is that legacy syntax? I'm not sure if a single mask needs 3 aliases

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomFullClipboardPatternParser.java [hunk 27]
```diff
@@ -0,0 +1,95 @@
...
+        if (arguments.length == 0 || arguments.length > 3) {
+            throw new InputParseException(Caption.of(
+                    "fawe.error.command.syntax",
+                    TextComponent.of(getPrefix() + "[pattern] (e.g. " + getPrefix() + "[#copy][true][false])")
+            ));
+        }
+        try {
+            boolean rotate = arguments.length == 2 && Boolean.getBoolean(arguments[1]);
+            boolean flip = arguments.length == 3 && Boolean.getBoolean(arguments[2]);
+            List<ClipboardHolder> clipboards = null;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/RandomFullClipboardPatternParser.java:58]: That initializer is redundant

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/DesaturatePattern.java [hunk 28]
```diff
@@ -15,7 +15,7 @@
     private final Extent extent;
     private final double value;
 
-    public DesaturatePattern(Extent extent, double value, TextureHolder util) {
+    public DesaturatePattern(Extent extent, TextureHolder util, double value) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/DesaturatePattern.java:18]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/OffsetPattern.java [hunk 29]
```diff
@@ -13,13 +13,17 @@
     private final int dx;
     private final int dy;
     private final int dz;
+    private final int minY;
+    private final int maxY;
     private final transient MutableBlockVector3 mutable = new MutableBlockVector3();
     private final Pattern pattern;
 
-    public OffsetPattern(Pattern pattern, int dx, int dy, int dz) {
+    public OffsetPattern(Pattern pattern, int dx, int dy, int dz, int minY, int maxY) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/OffsetPattern.java:21]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java [hunk 30]
```diff
@@ -18,16 +18,14 @@
...
 public class RandomFullClipboardPattern extends AbstractPattern {
 
-    private final Extent extent;
     private final List<ClipboardHolder> clipboards;
     private final boolean randomRotate;
     private final boolean randomFlip;
     private final Vector3 flipVector = Vector3.at(1, 0, 0).multiply(-2).add(1, 1, 1);
 
-    public RandomFullClipboardPattern(Extent extent, List<ClipboardHolder> clipboards, boolean randomRotate, boolean randomFlip) {
+    public RandomFullClipboardPattern(List<ClipboardHolder> clipboards, boolean randomRotate, boolean randomFlip) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java:26]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomOffsetPattern.java [hunk 31]
```diff
@@ -23,7 +25,7 @@
     private final transient MutableBlockVector3 mutable = new MutableBlockVector3();
     private final transient SplittableRandom r;
 
-    public RandomOffsetPattern(Pattern pattern, int dx, int dy, int dz) {
+    public RandomOffsetPattern(Pattern pattern, int dx, int dy, int dz, int minY, int maxY) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomOffsetPattern.java:28]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RelativePattern.java [hunk 32]
```diff
@@ -11,11 +11,15 @@
...
 
     private final Pattern pattern;
-    private BlockVector3 origin;
+    private final int minY;
+    private final int maxY;
     private final MutableBlockVector3 mutable = new MutableBlockVector3();
+    private BlockVector3 origin;
 
-    public RelativePattern(Pattern pattern) {
+    public RelativePattern(Pattern pattern, int minY, int maxY) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RelativePattern.java:19]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SaturatePattern.java [hunk 33]
```diff
@@ -18,10 +19,10 @@
     private final Extent extent;
 
 
-    public SaturatePattern(Extent extent, int color, TextureHolder texture) {
+    public SaturatePattern(Extent extent, TextureHolder texture, int r, int g, int b) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SaturatePattern.java:22]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/ShadePattern.java [hunk 34]
```diff
@@ -16,7 +16,7 @@
     private final Extent extent;
     private final boolean darken;
 
-    public ShadePattern(Extent extent, boolean darken, TextureUtil util) {
+    public ShadePattern(Extent extent, TextureUtil util, boolean darken) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/ShadePattern.java:19]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SolidRandomOffsetPattern.java [hunk 35]
```diff
@@ -47,6 +43,14 @@ public SolidRandomOffsetPattern(Pattern pattern, int dx, int dy, int dz) {
         this.mutable = new MutableBlockVector3();
     }
 
+    public static boolean[] getTypes() {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SolidRandomOffsetPattern.java:46]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java [hunk 36]
```diff
@@ -13,13 +13,17 @@
...
     private final int moves;
+    private final int minY;
+    private final int maxY;
 
     private final MutableBlockVector3 cur;
     private final MutableBlockVector3[] buffer;
     private final MutableBlockVector3[] allowed;
 
-    public SurfaceRandomOffsetPattern(Pattern pattern, int distance) {
+    public SurfaceRandomOffsetPattern(Pattern pattern, int distance, int minY, int maxY) {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java:23]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java [hunk 37]
```diff
@@ -13,13 +13,17 @@
...
         this.pattern = pattern;
+        this.minY = minY;
+        this.maxY = maxY;
         this.moves = Math.min(255, distance);
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java:27]: I assume that has been addressed in big worlds? Looking on the diff below

File: worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java [hunk 38]
```diff
@@ -477,7 +475,15 @@ private BaseBlock parseLogic(String input, ParserContext context) throws InputPa
 
             return validate(context, new SkullBlock(state, type.replace(" ", "_"))); // valid MC usernames
         } else {
-            return validate(context, state.toBaseBlock());
+            nbt = state.getNbtData();
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/extension/factory/parser/DefaultBlockParser.java:478]: Fawe annotations

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/SimpleInputParser.java [hunk 39]
```diff
@@ -32,19 +32,12 @@
  *
  * @param <E> the element
  */
-public abstract class SimpleInputParser<E> extends InputParser<E> {
+public abstract class SimpleInputParser<E> extends InputParser<E> implements AliasedParser {
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/internal/registry/SimpleInputParser.java:35]: Annotations

**Review by NotMyFault — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java (hunk 37 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/SurfaceRandomOffsetPattern.java:27]: This isn't to do with world height.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoXPatternParser.java (hunk 26 above)
Comment (dordsor21) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/pattern/NoXPatternParser.java:23]: it's what it was in legacy, no reason not to keep them all

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java [hunk 40]
```diff
@@ -367,14 +362,14 @@ public TextureUtil(File folder) throws FileNotFoundException {
...
+                            "Could not download version jar. Please do so manually by creating a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar in it.");
                     LOGGER.error("If the file exists, please make sure the server has read access to the directory.");
                 }
             } catch (AccessControlException e) {
                 LOGGER.error(
-                    "Could not download asset jar. It's likely your file permission are setup improperly and do not allow fetching data from the Mojang servers.");
+                        "Could not download asset jar. It's likely your file permission are setup improperly and do not allow fetching data from the Mojang servers.");
                 LOGGER.error(
-                    "Please create the following folder manually: `FastAsyncWorldEdit/textures` with `.minecraft/versions` jar in it.");
+                        "Please create the following folder manually: `FastAsyncWorldEdit/textures` with `.minecraft/versions` jar in it.");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:372]: Update instructions with new path. Also asset jar > version jar. We should stick to one term.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java [hunk 41]
```diff
@@ -520,10 +516,25 @@ public BlockType getDarkerBlock(BlockType block) {
...
+        if (block == BlockTypes.GRASS_BLOCK) {
+            return validBiomes[0].grassCombined;
+        }
         return blockColors[block.getInternalId()];
     }
 
+    public int getColor(BiomeType biome) {
+        return validBiomes[biome.getInternalId()].grassCombined;
+    }
+
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:537]: Javadocs

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java [hunk 42]
```diff
@@ -619,56 +630,34 @@ public void loadModTextures() throws IOException {
...
                     int bytesRead;
                     while ((bytesRead = in.read(dataBuffer, 0, 1024)) != -1) {
                         fileOutputStream.write(dataBuffer, 0, bytesRead);
                     }
+                    fileOutputStream.close();
+                    files = folder.listFiles((dir, name) -> name.endsWith(".jar"));
                 } catch (IOException e) {
                     LOGGER.error(
-                        "Could not download version jar. Please do so manually by creating a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar or mods in it.");
+                            "Could not download version jar. Please do so manually by creating a `FastAsyncWorldEdit/textures` folder with `.minecraft/versions` jar or mods in it.");
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:650]: Update instructions matching new destination.

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java [hunk 43]
```diff
@@ -32,24 +33,20 @@
...
 import java.util.List;
+import java.util.Locale;
 import java.util.Map;
 import java.util.Set;
-import java.util.concurrent.ConcurrentHashMap;
-import java.util.regex.Pattern;
 import java.util.zip.ZipEntry;
 import java.util.zip.ZipFile;
+
 import static org.apache.logging.log4j.LogManager.getLogger;
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:48]: Replace `#getLogger` with our LOGGER format. Maybe shift the error to a warn level, you can't do much about missing assets anyway.

**Review by NotMyFault — CHANGES_REQUESTED** [review]

**Review by NotMyFault — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java [hunk 44]
```diff
@@ -0,0 +1,63 @@
...
+            return null;
+        }
+        ResettableExtent[] transforms = new ResettableExtent[split.size()];
+        for (int i = 0; i < split.size(); i++) {
+            transforms[i] = worldEdit.getTransformFactory().parseFromInput(split.get(i), context);
+        }
+        RandomTransform randomTransform = new RandomTransform();
+        for (ResettableExtent transform : transforms) {
+            randomTransform.add(transform, 1d);
+        }
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/transform/RandomTransformParser.java:59]:
```suggestion
        RandomTransform randomTransform = new RandomTransform();
        for (int i = 0; i < split.size(); i++) {
            ResettableExtent transform = worldEdit.getTransformFactory().parseFromInput(split.get(i), context);
            randomTransform.add(transform, 1d);
        }
```
should work too?

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java [hunk 45]
```diff
@@ -40,7 +46,7 @@ public boolean apply(Extent extent, BlockVector3 get, BlockVector3 set) throws W
             transform = transform.rotateY(ThreadLocalRandom.current().nextInt(4) * 90);
             holder.setTransform(new AffineTransform().rotateY(ThreadLocalRandom.current().nextInt(4) * 90));
         }
-        if (randomFlip) {
+        if (randomFlip && ThreadLocalRandom.current().nextInt(2) == 1) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/pattern/RandomFullClipboardPattern.java:49]: nextBoolean()?

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java [hunk 46]
```diff
@@ -234,6 +234,27 @@ private SuggestionHelper() {
...
+    //FAWE start
+    /**
+     * Returns a stream of suggestions for booleans.
+     *
+     * @param argumentInput the given input to filter with.
+     * @return a stream of suggestions.
+     */
+    public static Stream<String> suggestBoolean(String argumentInput) {
+        if (argumentInput.isEmpty()) {
+            return Arrays.stream(new String[]{"true", "false"});
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/util/SuggestionHelper.java:246]: `Stream.of(...)`, also for the two `Stream.ofNullable(...)`s below

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/AliasedParser.java [hunk 47]
```diff
@@ -0,0 +1,14 @@
...
+import java.util.List;
+
+public interface AliasedParser {
+
+    /**
+     * The strings this parser matches.
+     *
+     * @return the matching aliases
+     */
+    List<String> getMatchedAliases();
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/AliasedParser.java:12]: Should probably return a `Collection<String>` or a `Set<String>`

**Review by SirYwell — CHANGES_REQUESTED** [review]
I'm not quite happy with the `Rich(Mask|Pattern|Transform)Parser`s, but I guess it would make more sense to have more upstream changes intsead of putting more work into this here.

Otherwise just a few minor things

**Review by SirYwell — APPROVED** [review]
