### PR TITLE
NullPointer fix for /schematic list

### LINKED ISSUE #780: NullPointer on //schem list with build 461
```
> /schem list
[14:23:05 INFO]: Please report this error: [See console]
[14:23:05 INFO]: java.lang.NullPointerException: null
[14:23:05 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
        at com.sk89q.worldedit.command.SchematicCommands.list(SchematicCommands.java:604) ~[?:?]
        at com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$list(SchematicCommandsRegistration.java:327) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractNonPlayerActor.lambda$runAction$1(AbstractNonPlayerActor.java:102) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

### PR DESCRIPTION
**Pull request by Ivan8or**
## Overview

This solves the nullpointer exception players get when listing schematics where the parent directory was not made yet

**Fixes #{issue number}**
fixes #780 
## Description

added checks to make sure if array returned by getFiles() is null it is not used

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

### CODE REVIEW

**Review by aurorasmiles — APPROVED** [review]

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 1]
```diff
@@ -601,11 +601,13 @@ public void list(Actor actor, LocalSession session,
         long totalBytes = 0;
         File parentDir = new File(dir.getAbsolutePath() + (playerFolder ? File.separator + uuid.toString() : ""));
         try {
-            for (File schem : getFiles(parentDir, null, null)) {
-                if (schem.getName().endsWith(".schem") || schem.getName().endsWith(".schematic")) {
-                    totalBytes += Files.size(Paths.get(schem.getAbsolutePath()));
+            List<File> toAddUp = getFiles(parentDir, null, null);
+            if(toAddUp != null &&  toAddUp.size() != 0)
```
Comment (N0tMyFaultOG) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:605]: if ( plus missing  brackets

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 2]
```diff
@@ -736,15 +738,15 @@ public Void call() throws Exception {
...
             int numFiles = -1;
             if (checkFilesize) {
-                File parentDir = new File(file.getParent());
-
-                for (File child : getFiles(rootDir, null, null)) {
-                    if (child.getName().endsWith(".schem") || child.getName().endsWith(".schematic")) {
-                        directorysizeKb += Files.size(Paths.get(child.getAbsolutePath())) / 1000.0;
-                        numFiles++;
+                List<File> toAddUp = getFiles(rootDir, null, null);
+                if(toAddUp != null &&  toAddUp.size() != 0) {
```
Comment (N0tMyFaultOG) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:742]: Missing space.

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 3]
```diff
@@ -736,15 +738,15 @@ public Void call() throws Exception {
...
+                    for (File child : toAddUp) {
+                        if (child.getName().endsWith(".schem") || child.getName().endsWith(".schematic")) {
+                            directorysizeKb += Files.size(Paths.get(child.getAbsolutePath())) / 1000.0;
```
Comment (N0tMyFaultOG) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:745]: 1000 should be sufficient.

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 4]
```diff
@@ -736,15 +738,15 @@ public Void call() throws Exception {
...
+                            numFiles++;
+                        }
                     }
                 }
-
                 if (overwrite) {
                     oldKbOverwritten = Files.size(Paths.get(file.getAbsolutePath())) / 1000.0;
```
Comment (N0tMyFaultOG) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:751]: 1000 should be sufficient.

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 5]
```diff
@@ -760,9 +762,12 @@ public Void call() throws Exception {
 
                 if (numFiles == -1) {
                     numFiles = 0;
-                    for (File child : getFiles(rootDir, null, null)) {
-                        if (child.getName().endsWith(".schem") || child.getName().endsWith(".schematic")) {
-                            numFiles++;
+                    List<File> toAddUp = getFiles(rootDir, null, null);
+                    if(toAddUp != null &&  toAddUp.size() != 0) {
```
Comment (N0tMyFaultOG) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:766]: Missing space.

**Review by N0tMyFaultOG — CHANGES_REQUESTED** [review]

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java (hunk 3 above)
Comment (Ivan8or) [reply worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:746]: it needs to be 1000.0 otherwise the result will remain an integer - even though it's being +='ed to a double - which I think is just silly but that's how it is :(

**Review by N0tMyFaultOG — APPROVED** [review]
