### PR TITLE
Un-break for versions <1.21.3

### LINKED ISSUE #2987: Failed to start server
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

when starting the server it gives FAWE error

### To Reproduce

I have only uploaded the latest version of fawe to my server

### Expected behaviour

that starts normally

### Screenshots / Videos

image

### Error log (if applicable)

https://mclo.gs/UHzBSze

### Fawe Debugpaste

I can't do it because my server doesn't start

### Fawe Version

FastAsyncWorldEdit v2.12.1-SNAPSHOT-964;8b18dbc

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SirYwell**
## Overview

Fixes #2987

## Description

Compile against 1.21 again to avoid bytecode incompatible with version <1.21.3. ~~Also apply an upstream patch and remove now-unneeded code.~~

The upstream patch initially included doesn't support custom biomes pre 1.21.3, so we need to revisit that separately.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java [hunk 1]
```diff
@@ -322,38 +319,6 @@ private void setupTags() {
         }
     }
 
-    // FAWE start
-    private void setupBiomes(boolean expectFail) {
```
Comment (dordsor21) [inline worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java:326]: We definitely don't need this any more? P2 still has biome types available during generation?

**Review by PierreSchwang — APPROVED** [review]

**Review by dordsor21 — APPROVED** [review]
