### PR TITLE
Fix incompatibility between WorldEdit and FAWE for LocalSession#getTool

### LINKED ISSUE #1398: FAWE breaks compatibility with WorldEdit on LocalSession#getTool
### What feature do you want to see added?

WorldEdit has only LocalSession#getTool(ItemType) and does not have any overload which matches any of the FAWE method signatures.

The original WorldEdit method signature should be readded again to avoid hacky workarounds when supporting FAWE and WorldEdit

### Are there any alternatives?

Using reflections, which is not really nice and makes it annoying to support FAWE and WorldEdit

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RainbowDashLabs**
## Overview
WorldEdit has only LocalSession#getTool(ItemType) and does not have any overload which matches any of the FAWE method signatures.

Fixes #1398

## Description
The original WorldEdit method signature is readded again to avoid hacky workarounds when supporting FAWE and WorldEdit

## Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java [hunk 1]
```diff
@@ -1120,6 +1120,24 @@ public Tool getTool(ItemType item, Player player) {
...
+    /**
+     * Get the tool assigned to the item.
+     *
+     * @param item the item type
+     * @return the tool, which may be {@code null}
+     */
+    @Nullable
+    @Deprecated
+    //FAWE start
+    //This method is here for byte code compatibility with WorldEdit.
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java:1132]: If that is an upstream method, the FAWE annotations are not needed. Yet, the deprecation note can point to the recommended Fawe method to use.

Comment (RainbowDashLabs) [reply worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java:1132]: I thought they are needed since the method body differs from WorldEdit. World Edit uses a simple HashMap to store the tools.

I will add a deprecation comment to the method.

Comment (NotMyFault) [reply worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java:1132]: > I thought they are needed since the method body differs from WorldEdit. World Edit uses a simple HashMap to store the tools.

That would then need to be disclosed within annotations as a one liner

**Comment by dordsor21** [comment]
The annotations also ought to be within the method body, else it implies the method is added by FAWE

File: worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java (hunk 1 above)
Comment (RainbowDashLabs) [reply worldedit-core/src/main/java/com/sk89q/worldedit/LocalSession.java]: I adjusted it and moved the annotations to the body.

It is not a one line since WorldEdit does not use a synchronized block. Should be fine now.

**Review by NotMyFault — APPROVED** [review]

**Review by dordsor21 — APPROVED** [review]
