### PR TITLE
Fix erosion and pull brushes

### LINKED ISSUE #559: ERODE Brush is not working.
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/d867f8c3233841cbaf5e61b16e4c76af

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
 FastAsyncWorldEditunknown created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
 Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
 ------------------ Platforms ------------------
* Bukkit-Official(1.16-309;3b7f723)

 ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running CraftBukkit version git-Spigot-9639cf7-8fb6585 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**[REQUIRED] Description of the problem:**
Unable to use the Erode brush- Nothing eroded
Used the command: `//brush erode` (with a hoe) and got this error when left, or right clicking with said hoe, 
https://pastebin.com/BNY1Z7MR

**How to replicate**:
Literally just try to use the brush, on anything...
do //brush erode
boom, replicated
**Plugins being used on the server:**
WorldEdit (FAWE), VoidGenerator, Essentials, UltraRegions, React, Iris, Arceon, BileTools, Worldborder, UlltraPermissions 

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)]
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by IronApollo**
**Fixes #559 **

## Description
Fixes the erosion and pull brushes ArrayIndexOutOfBoundsException, as well as revert their default values to their proper, respective values. Also, re-enabled the ability to edit the arguments ingame for the pull brush.

## Checklist
- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

### CODE REVIEW

**Review by N0tMyFaultOG — APPROVED** [review]

File: worldedit-core/src/main/java/com/boydti/fawe/object/brush/RaiseBrush.java [hunk 1]
```diff
@@ -5,6 +5,6 @@ public RaiseBrush() {
         this(6, 0, 1, 1);
     }
     public RaiseBrush(int erodeFaces, int erodeRec, int fillFaces, int fillRec) {
-        super(2, 1, 5, 1);
+        super(erodeFaces, erodeRec, fillFaces, fillRec);
```
Comment (MattBDev) [inline worldedit-core/src/main/java/com/boydti/fawe/object/brush/RaiseBrush.java:8]: weird that these were hard coded values to begin with.

**Review by MattBDev — APPROVED** [review]

**Review by aurorasmiles — APPROVED** [review]
