### PR TITLE
fix: set and clone Expression Environment after Expression cloning

### LINKED ISSUE #2616: Mask queries don't work anymore
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

`queryRel` Masks don't seem to work anymore. Whenever I try to use it, it doesn't work and spams the same NullPointerException `Cannot invoke "com.sk89q.worldedit.internal.expression.ExpressionEnvironment.getBlockTypeRel(double, double, double)" because "this.environment" is null`  in the console over and over again. 

- I tried it with different servers even with ones that only have FAWE installed
- I tried it with newest server versions and older server versions (1.19.4)
- I tried it with newest and older FAWE versions till half a year ago
=> No matter what I do I can always reproduce this error with any queryRel and any mask or gmask that should produce a result but fails.

I also looked at the code and compiled it with some debug messages. Whenever I type the queryRel command, new Function classes get created and the Environment variable in the Function class is set. But once I execute the command another Function class is created but this time no Environment is set which then obviously leads to a NullPointerException.

What should I do now? I really need this to work and I'm willing to help out to fix this problem. 

I talk about this line in the code but it will probably also fail for the other methods like `query` or `queryAbs`: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/Functions.java#L425

### To Reproduce

1. Create a brush (e.g. `//brush sphere stone`)
2. Create a mask with queryRel (e.g. `//mask =queryRel(0,1,0,0,0)` - Mask all blocks that have air above them)
3. Click with the brush and see the errors in the console. Nothing gets replaced even though it should work.

### Expected behaviour

Normally the queryRel should work. In my Steps to Reproduce example it should replace all surface blocks with stone. 
It says that it worked but no blocks get placed and an error gets printed in the console.

### Screenshots / Videos

image

Debug Messages:
- FUNCTIONS CREATED message in Functions.java constructor
- ENVIRONMENT SET message in Functions.setEnvironment() function
- Environment check on command execution
image

### Error log (if applicable)

https://paste.gg/p/anonymous/a1cdb839af32405a98c6bcbd68ac0357

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/89e8261d1a60492f859535bd46e51942

### Fawe Version

2.9.1-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MineFact**
## Overview

Fixes #2616

## Description
This Pull Requests sets the WorldEditExpressionEnvironment after an Expression gets cloned to make sure that the Functions class remains its environment after cloning  to not run into a NullPointerException.
When the Expression is cloned, the WorldEditExpressionEnvironment gets cloned as well while making sure that the offset of the environment is not changing during the cloning process.

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java [hunk 1]
```diff
@@ -28,6 +28,8 @@
 
 public class WorldEditExpressionEnvironment implements ExpressionEnvironment {
 
+    private final Vector3 UN_OFFSET = Vector3.at(0.5, 0.5, 0.5);
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java:31]: Maybe `BLOCK_CENTER_OFFSET` might be a better name?

File: worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExpressionEnvironment.java [hunk 2]
```diff
@@ -36,4 +36,5 @@ public interface ExpressionEnvironment {
 
     int getBlockDataRel(double x, double y, double z);
 
+    ExpressionEnvironment clone();
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/internal/expression/ExpressionEnvironment.java:39]: Could you put `// FAWE` comments around this method, similar to how it is done in the implementation?

**Review by SirYwell — COMMENTED** [review]
A few small suggestions

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java [hunk 3]
```diff
@@ -28,6 +28,8 @@
 
 public class WorldEditExpressionEnvironment implements ExpressionEnvironment {
 
+    private final Vector3 BLOCK_CENTER_OFFSET = Vector3.at(0.5, 0.5, 0.5);
```
Comment (PierreSchwang) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/shape/WorldEditExpressionEnvironment.java:31]: should be made static, it's already uppercase, and we don't have to allocate a Vector for each instance of the environment (especially due to potential clones)

**Comment by PierreSchwang** [comment]
I'd say ExpressionEnvironment should implement Clonable, if there is already the clone method

**Review by SirYwell — APPROVED** [review]
Looks good, thanks!

**Review by NotMyFault — APPROVED** [review]

**Review by TheMeinerLP — APPROVED** [review]

**Review by dordsor21 — APPROVED** [review]
