### PR TITLE
Fixes to BlockMask and "char" masks

### LINKED ISSUE #1626: Blocks with multiple rotation states are not covered by //replace, //count or //mask when not specifying the exact rotation and not in default rotation
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

it doesnt count the skulls correct, if they dont face noth

### To Reproduce

1. //count two skulls facing north = 2
2. //count two skulls facing other direction than north = 0

Edit: The facing direction seems to be irrelevant, as long as the skull has a rotation larger than 0

### Expected behaviour

should count the skulls no matter the facing 

### Screenshots / Videos

https://user-images.githubusercontent.com/64259198/155409069-14992a22-d280-4663-b785-fa8edbaaf11a.mp4

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/9e035279528b4880a5ee6f7cabf77fb2

### Fawe Version

FastAsyncWorldEdit-2.0.2-SNAPSHOT-103

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### LINKED ISSUE #1755: `//gmask` has error : unsetType cannot be null when passed to InverseSingleBlockTypeMask
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Error executing `//gmask`

### To Reproduce

1. player run command : `/gmask !spruce_leaves,stone,grass`
2. error log

### Expected behaviour

Works normally without errors

### Screenshots / Videos

image

### Error log (if applicable)

https://gist.github.com/MiunaPA/43286d1c704105fcf695cf1af9a5498e

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c3dfd937b6af43f99ce0d602e6770d70

### Fawe Version

2.2.1-SNAPSHOT-183

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Some commands work
1. `/gmask !cyan_concrete,cyan_wool`
2. `/gmask !sand,stone`
3. `/gmask !spruce_leaves[distance=1,persistent=false],spruce_log`

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #1755
 - Fixes #1626

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
 import java.util.concurrent.TimeoutException;
 import java.util.function.BiPredicate;
 import java.util.function.Predicate;
+import java.util.regex.Pattern;
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/function/mask/BlockMaskBuilder.java:41]: Unneeded import?
