### PR TITLE
Fix clipboards to allow proper heights by allowing extended CuboidRegion heights

### LINKED ISSUE #1534: Freshly-saved schematic fails to load
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

A brand-new schematic that was just saved by the server cannot be loaded, either by other servers or the server that just wrote the file. It fails with a console stacktrace (linked below).

### To Reproduce

1. Select an area
2. `//copy`
3. `//schem save foo`
3a. (optional) copy file to another server
4. `//schem load foo`
5. Receive error

### Expected behaviour

The schematic that was just saved by the server should load correctly.

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://paste.gg/p/anonymous/a5b4a75d606b418796c76495dfe00f47

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bae35903f00c47f381b0cf2d867a0376

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-63;5fc0de0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
Fixes #1534

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java [hunk 1]
```diff
@@ -85,6 +85,29 @@ public CuboidRegion(World world, BlockVector3 pos1, BlockVector3 pos2) {
...
     }
 
+    //FAWE start - allow region to be created without clamping Y
+    /**
+     * Construct a new instance of this cuboid using two corners of the cuboid.
+     *
+     * @param world the world
+     * @param pos1  the first position
+     * @param pos2  the second position
+     * @since TODO
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/regions/CuboidRegion.java:95]: The boolean parameter is missing

**Review by NotMyFault — COMMENTED** [review]
Going to give it a practical test later on

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.
