### PR TITLE
Fix #saturate-Pattern

### LINKED ISSUE #1933: #saturate not working after looking for wrong json files in the textures folder
### Server Implementation

Spigot

### Server Version

1.19.2

### Describe the bug

Using #saturate in any instance where it would be applicable, such as replacing some existing terrain with a saturation effect, (//r #saturate[156][100][0][120]), results in an error. After looking at console, there were various blocks that the plugin tried to check for in fawe's texture folder and it could not find apparently. These can be seen in the debugpaste I've provided. I double-checked that the jar I provided was the latest, and it was (1.19.2.jar). It appears that what all of the blocks share in common is that they all have some form of block state. I looked into the jar file through winrar to see if some of these block states were in the blockstates folder (1.19.2.jar\assets\minecraft\blockstates) and they were.

I suppose either my textures folder I uploaded was incorrect, although I obtained it from my own .minecraft/versions folder, or the plugin is just looking for the incorrect json files for the proper saturation. To counter the former, I deleted the textures jar I provided and let the plugin download the jar from mojang (https://athion.net/ISPaster/paste/view/5ccd411609ff47a3825b4afa1aaa0b1b). The same error seemed to persist.

### To Reproduce

- Select an area
- Try and apply some saturation pattern to it (//r #saturate[156][100][0][120])
- Receive error

### Expected behaviour

The saturation effect should work as normal, instead of giving an error.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3f1b1ddc83eb44779f10f29eda6a31ce

### Fawe Version

FastAsyncWorldedit version 2.4.5-SNAPSHOT-275;5da558e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #1933 

## Description
1. Updated the asset url to the last release
2. Search through item models as well (No idea why, but many block state models are located in models/item)
3. Change BlockType access by using the BlockTypeCache directly - as the used ids are based on the indexes in the values array of BlockTypeCache. No idea if this changes anything, was just more logical to me.

Example for `#saturate[255][0][120][255]`
grafik
grafik

Based on my quick testing the changes works so far - Should logs and leaves be replaced as well? For me they don't, but I've never worked with that pattern before, so not that sure what the expected outcome is tbh

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java [hunk 1]
```diff
@@ -810,7 +810,7 @@ public void loadModTextures() throws IOException {
                 new File(Fawe.platform().getDirectory() + "/" + Settings.settings().PATHS.TEXTURES + "/")
                         .mkdirs();
                 try (BufferedInputStream in = new BufferedInputStream(
-                        new URL("https://piston-data.mojang.com/v1/objects/c0898ec7c6a5a2eaa317770203a1554260699994/client.jar")
+                        new URL("https://piston-data.mojang.com/v1/objects/055b30d860ead928cba3849ba920c88b6950b654/client.jar")
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:813]: Is this 1.19.2?

Comment (PierreSchwang) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:813]: Yep

Comment (NotMyFault) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:865]: Thanks!

**Review by NotMyFault — APPROVED** [review]
Thanks for addressing!

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java (hunk 1 above)
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:813]: We already downloaded the client jar at this point if I see this right, couldn't we therefore get rid of this somehow?

Comment (PierreSchwang) [reply worldedit-core/src/main/java/com/fastasyncworldedit/core/util/TextureUtil.java:813]: Gonna rebase the pr, yes - Alex cherry picked the client jar download from a commit I've made in this PR

**Review by SirYwell — APPROVED** [review]
Looks good
