### PR TITLE
Fix //snapshot in 1.18 and re-implement biome/entity restoration

### LINKED ISSUE #1568: //restore doesn't work with 1.18.1 worlds
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Restoring 1.18.1 worlds doesn't work, regardless of which blocks should be restored and in which size. 
No error appears in the console, but the following messages appear in the chat:
```
Snapshot 'weltn-untergrund' loaded; will be restored ...
Errors prevented the recovery of blocks.
Last error: Missing root 'Level' tag
```
The `//restore` of the same world works under the same FAWE and paper version when using a 1.17.1 backup that has not yet been updated to 1.18.1.

### To Reproduce

1. Load your 1.18.1 world into the backup folder
2. Select a region
3. //restore
-> the attempt ends in the described error

### Expected behaviour

The blocks in the selection should be restored from backup.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

 https://athion.net/ISPaster/paste/view/871f99ed8cca43ce951881bea6d0ca15

### Fawe Version

FastAsyncWorldEdit version 2.0.1-SNAPSHOT-76;e8f72d6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
Fixes #1568

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java [hunk 1]
```diff
@@ -32,4 +39,43 @@
...
     }
 
+    /**
+     * Get an integer from a tag.
+     *
+     * @param tag the tag to read from
+     * @param key the key to look for
+     * @return child tag
+     * @throws InvalidFormatException if the format of the items is invalid
+     */
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java:49]: `@since`

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java [hunk 2]
```diff
@@ -32,4 +39,43 @@
...
+        }
+        throw new InvalidFormatException(key + " tag is not of int, short or byte tag type.");
+    }
+
+    /**
+     * Get a mutable map of the values stored inside a {@link CompoundBinaryTag}
+     *
+     * @param tag {@link CompoundBinaryTag} to get values for
+     * @return Mutable map of values
+     */
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java:74]: `since todo`

**Review by NotMyFault — CHANGES_REQUESTED** [review]
- `//restore -b` doesn't work https://paste.gg/p/anonymous/b8330f24c792454fa1704411076ea34e
- `//restore -e` does not restore armor stands

**Comment by dordsor21** [comment]
Armourstand restoration works fine for me? Did you use `//restore -e`?

**Comment by NotMyFault** [comment]
> Armourstand restoration works fine for me? Did you use `//restore -e`?

Yeah, do I need to do anything special to make it work? The items I put in the chest were restored fine.

**Comment by dordsor21** [comment]
other tthan //restore -e, no

**Comment by NotMyFault** [comment]
https://streamable.com/a93mkp This is what I did to test entity restoring. Unless I'm mistaken, it _should_ work like that, no?

**Comment by dordsor21** [comment]
Seems to be a bug specifically with zipped backups

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]
