### PR TITLE
fix: allow use of quotes to allow spaces to be used as "and"

### LINKED ISSUE #1883: #mask pattern not working with anded by space masks
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Complex masks like "air >pink_concrete" are not correctly parsed by fawe inside of #mask.
I assume that #mask function parser (and maybe others) exits when it reaches space.

### To Reproduce

1. Select region
1. `/set "#mask[air >pink_concrete][green_concrete][red_concrete]"`

### Expected behaviour

`"#mask[air >pink_concrete][green_concrete][red_concrete]"` should correctly set green blocks above pink, everywhere else red.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/47264fe217cd4142a99f2bfa510a7184

### Fawe Version

2.4.2-SNAPSHOT-247

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- e.g. `//set "#mask[grass_block&<air][green_concrete][red_concrete]"`
 - fixes #1883

### CODE REVIEW

File: worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java [hunk 1]
```diff
@@ -161,7 +161,7 @@ protected Stream<String> getSuggestions(String argumentInput, int index, ParserC
      * @return an array of extracted arguments.
      * @throws InputParseException if {@code requireClosing == true} and the count of [ != the count of ]
      */
-    protected String[] extractArguments(String input, boolean requireClosing) throws InputParseException {
+    protected static String[] extractArguments(String input, boolean requireClosing) throws InputParseException {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/fastasyncworldedit/core/extension/factory/parser/RichParser.java:164]: This is an API incompatible change

**Review by SirYwell — CHANGES_REQUESTED** [review]

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
