### PR TITLE
Re-implement incremental schematic names in a folder

### LINKED ISSUE #1545: Create incremental schematics
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When i want create a bundle in fawe 1.12.2, i use this command :
`//schem save name_foler/`

This create a schematics ( if not exist already ) named "1.schem"
If i retape the command "2.schem", "3.schem" ...

Now it create a schematics ".schem" without name.

Can create some troubles if i use some pattern like the `#fullcopy[name_folder/]` causing to use the single schem ".schem" in place of the folder

### To Reproduce

1. Selection and copy things
2. Do the command `//schem save folder/`
3. It saved the ".schem" in folder "folder"

### Expected behaviour

Should create a schematics "1.schem" or "2.schem" if exist or "3.schem" if exist ....

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cbd97c8b178b41d28ed562b1eebc38a2

### Fawe Version

FastAsyncWorldEdit-1.17-426

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #1545

### CODE REVIEW

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 1]
```diff
@@ -472,7 +472,17 @@ public void save(
 
         //FAWE end
```
Comment (NotMyFault) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:473]: That does no longer apply.

**Review by NotMyFault — APPROVED** [review]

File: worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java [hunk 2]
```diff
@@ -470,9 +470,18 @@ public void save(
             }
         }
 
-        //FAWE end
         File f = worldEdit.getSafeSaveFile(actor, dir, filename, format.getPrimaryFileExtension());
-
+        int i = f.getName().lastIndexOf('.');
+        if (i == -1 && f.getName().isEmpty() || i == 0) {
```
Comment (SirYwell) [inline worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java:475]: Can a file name be emtpy?
We're checking both `i == - 1` and the empty name two times, maybe it can be extracted into variables for readability.

**Review by SirYwell — CHANGES_REQUESTED** [review]

**Review by SirYwell — APPROVED** [review]
